# name, reason, evidence ids, url, signals
P = [
("Qwen3.5 / Qwen3.6 / Qwen3.8 (native VL)","already mapped: `qwen` (base_pretrained). Vendor calls Qwen3.5 'a native vision-language model'; Qwen3.6-27B pipeline image-text-to-text. Stay.","W0010, F0226, F0001","https://huggingface.co/api/models/Qwen/Qwen3.6-27B",["W0004","W0010","F0001","F0005"]),
("Gemma 3 / Gemma 4 (vision, any-to-any E2B/E4B)","already mapped: `gemma`. gemma-4-31B-it is image-text-to-text, Apache-2.0 (F0223); E2B/E4B/12B any-to-any (F0003). Stay.","F0223, F0003","https://huggingface.co/api/models/google/gemma-4-31B-it",["W0001","F0001","F0003","F0005"]),
("Llama 3.2 Vision / Llama 4 Scout, Maverick","SKU of `llama` (Llama-3.2-11B/90B-Vision, Llama-4 image-text-to-text).","F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["W0001","F0002"]),
("Phi-3.5-vision / Phi-4-multimodal","SKU of `phi`: card lists multimodal-instruct among the Phi-4 family (F0218).","F0018, F0218","https://huggingface.co/microsoft/Phi-4-multimodal-instruct",["brief","F0001","F0018"]),
("ERNIE-4.5-VL","SKU of `ernie`: card presents it among 'ERNIE 4.5 models' with joint multimodal MoE pretraining (F0219).","F0035, F0219","https://huggingface.co/baidu/ERNIE-4.5-VL-28B-A3B-PT",["F0002","F0035"]),
("Kimi K3 / K2.5 / K2.6 (image-text-to-text)","already mapped: `kimi` (F0225).","F0225, F0001","https://huggingface.co/api/models/moonshotai/Kimi-K3",["W0007","F0001"]),
("GLM-5.3-Flash / GLM-5V-Turbo","already mapped: `glm`; GLM-5.3-Flash image-text-to-text (F0224).","F0224, W0014","https://huggingface.co/api/models/zai-org/GLM-5.3-Flash",["W0014","F0001"]),
("DeepSeek-V4-Flash-Vision-Exp / V4.1-Flash","SKU of `deepseek`.","F0001, F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=downloads&direction=-1&limit=200",["F0001","F0002"]),
("Inkling (Thinking Machines)","already mapped: `inkling` (base_pretrained).","W0007, F0001","https://huggingface.co/blog/state-of-open-models-summer-2026",["W0007","F0001"]),
("MiniMax-M3","already mapped: `minimax`.","F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["F0002"]),
("MiniCPM5","already mapped: `minicpm` (text line).","F0011","https://huggingface.co/api/models?author=openbmb&search=MiniCPM-o",["F0011"]),
("Muse Glimmer (Meta, 30B, Apache-2.0)","boundary -> finetuned_chat / base_pretrained: agentic general model 'with built-in vision support' (W0011). Absent from the map: flag to maintainer.","W0011, F0001","https://venturebeat.com/technology/meta-returns-to-open-source-with-muse-glimmer-an-apache-2-0-licensed-30b-parameter-ai-model-optimized-for-agents-available-now",["W0007","W0011","F0001"]),
("Step-3.7-Flash (StepFun)","boundary -> finetuned_chat (general flagship, image-text-to-text).","F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["F0002"]),
("Ling-3.0-flash-VL (inclusionAI)","SKU of the Ling family (absent from map).","F0005","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=trendingScore&direction=-1&limit=100",["F0005"]),
("Apriel-1.5-15b-Thinker (ServiceNow)","boundary -> finetuned_chat (general reasoning model with vision).","F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["F0002"]),
("HyperCLOVAX-SEED-Think-32B (Naver)","boundary -> finetuned_chat.","F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["F0002"]),
("Apertus-v1.5-8B (Swiss AI)","boundary -> base_pretrained (general LLM listed under image-text-to-text).","F0001","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=downloads&direction=-1&limit=200",["F0001"]),
("Command A Vision (Cohere)","SKU of tail `command-a`.","F0042","https://huggingface.co/api/models?author=CohereLabs&search=vision",["F0042"]),
("Seed1.5-VL (Doubao vision API)","closed; SKU of mapped `doubao-seed` (API model id doubao-1-5-thinking-vision-pro, W0024).","W0024","https://github.com/ByteDance-Seed/Seed1.5-VL",["W0024"]),
("Qwen3.5-Omni / Qwen3.8-Omni-Flash","closed tier of `qwen-omni`: Qwen3.5-Omni 'released ... as proprietary' (W0017); no Qwen3.5- or Qwen3.8-Omni weights under author=Qwen (F0244, only Qwen2.5-/Qwen3-Omni).","W0004, W0017, F0244","https://www.marktechpost.com/2026/03/30/alibaba-qwen-team-releases-qwen3-5-omni-a-native-multimodal-model-for-text-audio-video-and-realtime-interaction/",["W0004","W0017","F0244"]),
("Holo3-122B-A10B","SKU of `holo` (API-only flagship, W0026).","W0026","https://hcompany.ai/holo3.1",["W0026"]),
("Qwen-VL-Max / Qwen-VL-Plus","closed API tier of `qwen-vl` (OpenVLM snapshot).","F0215","http://opencompass.openxlab.space/assets/OpenVLM.json",["OpenVLM"]),
("GLM-4v-Plus","closed API tier of `glm-v` (OpenVLM snapshot).","F0215","http://opencompass.openxlab.space/assets/OpenVLM.json",["OpenVLM"]),
("SenseNova-V6 / V6.5-Pro","closed long-tail (OpenVLM, OpenSource=No).","F0215","http://opencompass.openxlab.space/assets/OpenVLM.json",["OpenVLM"]),
("Step-1o / Step-1.5V","closed long-tail (OpenVLM, OpenSource=No).","F0215","http://opencompass.openxlab.space/assets/OpenVLM.json",["OpenVLM"]),
("HunYuan-Standard-Vision","closed long-tail (OpenVLM, OpenSource=No).","F0215","http://opencompass.openxlab.space/assets/OpenVLM.json",["OpenVLM"]),
("CongRong-v2.0","closed long-tail (OpenVLM, OpenSource=No).","F0215","http://opencompass.openxlab.space/assets/OpenVLM.json",["OpenVLM"]),
("GPT-5 / Gemini-2.5-Pro / Claude 3.7 Sonnet (leaderboard top)","already mapped: `gpt-5`, `gemini-pro`, `claude-sonnet` (finetuned_chat).","F0215","http://opencompass.openxlab.space/assets/OpenVLM.json",["OpenVLM"]),
("InternVL-U","SKU of `internvl` (4B unified understanding+generation variant, W0013).","W0013","https://github.com/OpenGVLab/InternVL-U",["W0013"]),
("CogVLM2 / CogAgent / GLM-Edge-V","SKU (predecessors) of `glm-v`.","F0023, F0004","https://huggingface.co/api/models?author=zai-org&search=V",["F0023","F0004","OpenVLM"]),
("BLIP3o / BLIP3o-NEXT (Salesforce)","boundary -> media_generation (generation and editing line; 2025-11 checkpoints).","F0039","https://huggingface.co/api/models?author=Salesforce&search=blip",["F0039"]),
("xGen-MM (Salesforce)","SKU of `blip` (proposed fold; same vendor lab, 1,772 / 30d).","F0040","https://huggingface.co/api/models?author=Salesforce&search=xgen-mm",["F0040"]),
("Qwen2.5-VL-7B-Instruct-NVFP4 (nvidia)","SKU of `qwen-vl` (third-party quantization).","F0028","https://huggingface.co/api/models?author=nvidia&search=VL",["F0028"]),
("Llama-3.1-Nemotron-Nano-VL-8B","member of `nemotron-vl`.","F0028","https://huggingface.co/api/models?author=nvidia&search=VL",["F0028"]),
("VideoChat-Flash / VideoChat-R1 / VideoChat3","identity unclear: OpenGVLab and MCG-NJU both publish VideoChat checkpoints (F0004); not resolved this run.","F0004, W0019","https://www.alphaxiv.org/abs/2607.14935",["F0004","W0019"]),
("AutoGLM-Phone-9B","identity unclear (phone agent model; relation to GLM-V not verified).","F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["F0002"]),
("Qianfan-VL (Baidu)","identity unclear (separately named 3B/8B; not researched beyond listing, 539 / 30d).","F0035","https://huggingface.co/api/models?author=baidu&search=VL",["F0035"]),
("JoyAI-VL-Interaction (JD)","identity unclear (not researched beyond listing).","F0004","https://huggingface.co/api/models?pipeline_tag=video-text-to-text&sort=downloads&direction=-1&limit=100",["F0004"]),
("Marlin-2B (NemoStation)","identity unclear (not researched beyond listing).","F0004","https://huggingface.co/api/models?pipeline_tag=video-text-to-text&sort=downloads&direction=-1&limit=100",["F0004"]),
("ZDTaichu5.0-9B (TaichuAI)","identity unclear (not researched beyond listing).","F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["F0002","F0005"]),
("Mage-VL (Microsoft)","identity unclear (not researched beyond listing).","F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["F0002"]),
("LensVLM-9B (Apple)","identity unclear (not researched beyond listing).","F0005","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=trendingScore&direction=-1&limit=100",["F0005"]),
("LocateAnything-3B (NVIDIA)","identity unclear (grounding model; possible classic_ml_cv).","F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["F0002","F0005"]),
("OpenOmni (academic, NeurIPS 2025)","no addressable model artifact verified this run.","W0002","https://github.com/RainBowLuoCS/OpenOmni",["W0002"]),
("Show-o2 / MMaDA","not verified this run; unified gen models, contested with media_generation.","W0020","https://arxiv.org/pdf/2506.15564",["W0020"]),
("Cosmos-Reason 1/2 (NVIDIA)","boundary -> robotics_embodied / world_models (928,415 / 30d).","F0062","https://huggingface.co/api/models?author=nvidia&search=Cosmos-Reason",["F0001","F0005","F0062"]),
("MolmoAct / MolmoAct2 (Ai2)","boundary -> robotics_embodied (pipeline robotics).","F0012","https://huggingface.co/api/models?author=allenai&search=Molmo",["F0012"]),
("HY-Embodied-0.5 (Tencent)","boundary -> robotics_embodied.","F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["F0002"]),
("Isaac (Perceptron)","boundary -> robotics_embodied: Isaac 0.5 is 'for video understanding, embodied reasoning, and robot control' (W0025); HF pipeline robotics (F0061); repo perceptron-ai-inc/isaac (F0229).","W0025, F0061, F0229","https://huggingface.co/PerceptronAI/Isaac-0.5",["W0025","F0061"]),
("MedGemma","boundary -> scientific_ai_models (domain model; absent from map).","F0001","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=downloads&direction=-1&limit=200",["F0001","F0005"]),
("diffusiongemma / omni-dreams","boundary -> media_generation.","F0001, F0031","https://huggingface.co/api/models?author=nvidia&search=Omni",["F0001","F0031"]),
("chandra / chandra-ocr-2 (Datalab)","boundary -> document_conversion.","F0001","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=downloads&direction=-1&limit=200",["F0001","F0002"]),
("surya-ocr-2 (Datalab)","boundary -> document_conversion.","F0001","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=downloads&direction=-1&limit=200",["F0001"]),
("Unlimited-OCR / Qianfan-OCR (Baidu)","boundary -> document_conversion.","F0001, F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=downloads&direction=-1&limit=200",["F0001","F0002","F0005"]),
("HunyuanOCR","boundary -> document_conversion.","F0001","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=downloads&direction=-1&limit=200",["F0001","F0002"]),
("GOT-OCR2.0 (StepFun)","boundary -> document_conversion.","F0001","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=downloads&direction=-1&limit=200",["F0001","F0002"]),
("Nanonets-OCR / OCR2","boundary -> document_conversion.","F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["F0002"]),
("LightOnOCR-2","boundary -> document_conversion.","F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["F0002"]),
("PaddleOCR-VL","SKU of mapped `paddleocr` (document_conversion).","F0002, F0005","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["F0002","F0005"]),
("granite-docling / SmolDocling","boundary -> document_conversion (next to mapped `docling`).","F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["F0002"]),
("MinerU2.5","SKU of mapped `mineru`.","F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["F0002"]),
("RolmOCR / OCRFlux / Dolphin / OvisOCR2 / typhoon-ocr / jina-ocr / TeleOCR","boundary -> document_conversion (class of OCR-first VLMs).","F0001, F0002, F0005","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["F0001","F0002","F0005"]),
("dots.ocr / DeepSeek-OCR / olmOCR","already mapped (document_conversion).","F0001, F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=downloads&direction=-1&limit=200",["F0001","F0002"]),
("nemotron-colembed-vl / llama-nemotron-embed-vl / rerank-vl / omni-embed-nemotron","boundary -> embeddings_retrieval.","F0028, F0031","https://huggingface.co/api/models?author=nvidia&search=VL",["F0028","F0031"]),
("Ming-omni-tts / Ming-UniAudio / Step-Audio-2-mini / A.X-K2-Raon-Speech / moondream parakeet / VITA-QinYu","boundary -> speech_audio.","F0045, F0003, F0016, F0050","https://huggingface.co/api/models?pipeline_tag=any-to-any&sort=downloads&direction=-1&limit=100",["F0003","F0016","F0045","F0050"]),
("UI-TARS-desktop","boundary -> orchestration_agents (agent app, software).","W0018","https://themenonlab.blog/blog/ui-tars-desktop-open-source-gui-agent",["W0018"]),
("OmniParser (Microsoft)","boundary -> orchestration_agents / classic_ml_cv (screen parser, not a VLM).","F0002","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=likes&direction=-1&limit=200",["F0002"]),
("vllm-omni / mlx-vlm / lmms-eval / VLMEvalKit","already mapped (vllm, mlx-vlm, lmms-eval, vlmevalkit).","W0002, W0003","https://github.com/vllm-project/vllm-omni",["W0002","W0003"]),
("Community fine-tunes and quantizations (unsloth, DavidAU, HauhauCS, bartowski, lmstudio-community ...)","not products: derivatives of mapped families (class).","F0001, F0002, F0005","https://huggingface.co/api/models?pipeline_tag=image-text-to-text&sort=downloads&direction=-1&limit=200",["F0001","F0002","F0005"]),
]
