"""regenerate.yml must tell the consumer the commit that CONTAINS the published payload.

The workflow is triggered at $GITHUB_SHA (the commit whose push matched the path filter),
then serializes and pushes a *new* bot commit carrying the freshly generated bytes. The
dispatch to aipotluck.org therefore has two distinct commits available, and it must send the
right one:

  * source_sha  -> the bot payload commit (steps.commit.outputs.published_sha). This is the
    commit whose tree holds build/notebook_data.json as published. A consumer that records or
    fetches this SHA gets the bytes that were just published.
  * trigger_sha -> $GITHUB_SHA, the commit that triggered the run. Its tree still holds the
    PREVIOUS generated payload, so it is false provenance for the published data and is only
    useful as "what caused this regeneration".

The bug this guards against sent $GITHUB_SHA as source_sha, giving the consumer the commit
with the stale payload. These assertions pin the distinction so a future edit cannot silently
reintroduce it.
"""

from __future__ import annotations

import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
WORKFLOW = ROOT / ".github/workflows/regenerate.yml"


def _steps() -> list[dict]:
    doc = yaml.safe_load(WORKFLOW.read_text())
    return doc["jobs"]["regenerate"]["steps"]


def _step_run(name_substring: str) -> str:
    for step in _steps():
        if name_substring in (step.get("name") or ""):
            return step.get("run") or ""
    raise AssertionError(f"no step whose name contains {name_substring!r}")


def test_commit_step_outputs_the_published_commit_sha():
    """The commit step must export the pushed bot commit's SHA so the notifier can send it."""
    run = _step_run("Commit regenerated artifacts")
    assert 'published_sha=$(git rev-parse HEAD)' in run, (
        "the commit step must output published_sha=$(git rev-parse HEAD) after pushing, so the "
        "dispatch can identify the commit that contains the published payload"
    )
    # The output is only meaningful once the bot commit exists, i.e. after the push.
    assert run.index("git push") < run.index("published_sha="), (
        "published_sha must be captured AFTER git push, so it names the pushed payload commit"
    )


def test_dispatch_sends_the_payload_commit_as_source_sha_not_the_trigger_commit():
    run = _step_run("Notify aipotluck.org")
    payload = re.search(r'client_payload\\?"?\s*:\s*\{.*\}', run, re.S)
    assert payload, "could not locate the client_payload object in the dispatch step"
    body = payload.group(0)

    # source_sha carries the published payload commit, never the raw trigger commit.
    assert re.search(r'source_sha\\?"\s*:\s*\\?"\$(\{?PUBLISHED_SHA\}?)', body), (
        "source_sha must be the published bot commit (PUBLISHED_SHA from "
        "steps.commit.outputs.published_sha), not $GITHUB_SHA"
    )
    assert "source_sha" in body and "$GITHUB_SHA" not in body.split("source_sha")[1].split(",")[0], (
        "source_sha must not be set to $GITHUB_SHA (the trigger commit holds the stale payload)"
    )

    # PUBLISHED_SHA is bound from the commit step's output.
    assert "steps.commit.outputs.published_sha" in run, (
        "the notify step must read steps.commit.outputs.published_sha"
    )


def test_trigger_commit_is_still_available_as_trigger_sha():
    """The trigger commit is not wrong information, only mislabeled if sent as source_sha.
    Keep it, under an honest key, so nothing is lost."""
    run = _step_run("Notify aipotluck.org")
    assert re.search(r'trigger_sha\\?"\s*:\s*\\?"\$GITHUB_SHA', run), (
        "trigger_sha must carry $GITHUB_SHA so the trigger commit is still reported, distinctly "
        "from the published payload commit"
    )
