import marimo

__generated_with = "unknown"
app = marimo.App(width="full")


@app.cell(hide_code=True)
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


@app.cell(hide_code=True)
def imports():
    import pandas as pd
    import plotly.graph_objects as go
    return go, pd


@app.cell(hide_code=True)
def style():
    F = {
        "headline": "'Noto Serif', Georgia, serif",
        "body": "'Plus Jakarta Sans', -apple-system, system-ui, sans-serif",
        "mono": "'DM Mono', ui-monospace, SFMono-Regular, monospace",
    }
    C = {
        # Shared neutrals + structure (match ai-stack-map / products-view).
        "ink": "#0b252f",
        "ink_2": "#272726",
        "ink_3": "#8fa1a4",
        "paper": "#f7f6f6",
        "paper_2": "#f2f1f1",
        "rule": "#edecec",
        "white": "#ffffff",
        "border": "#a5bbbe",
        # Brand salmon ramp: deep = emphasis/highlight, fading to pale coral.
        "healthy": "#e86f57",
        "warm": "#f4886f",
        "signal": "#f8ad99",
        # Navy accent + cool slate pair for magnitude/secondary series.
        "accent": "#0b252f",
        "slate": "#3f5d68",
        "slate_mid": "#5f7e88",
        "slate_lt": "#a5bbbe",
    }
    LAYOUT = dict(
        plot_bgcolor="white",
        paper_bgcolor="white",
        font=dict(family=F["body"], size=12, color=C["ink"]),
        margin=dict(t=20, l=60, r=20, b=50),
        legend=dict(
            bgcolor="rgba(0,0,0,0)",
            font=dict(size=11),
            orientation="h",
            yanchor="bottom", y=1.02,
            xanchor="left", x=0,
        ),
        hovermode="closest",
    )
    CHART_LAYOUT = LAYOUT
    CAT_COLORS = {
        # Brand-harmonised categorical palette: cool navy->slate ramp for the
        # build/infra layers, salmon for the consumer-facing model/app layers,
        # muted slates for the long-tail buckets. No rainbow, keeping the
        # restrained two-family brand system of the AI Stack Map.
        "Infrastructure": "#0b252f",     # navy
        "AI Engineering": "#3f5d68",     # dark slate
        "Model Development": "#5f7e88",  # mid slate
        "Models": "#e86f57",             # deep salmon (headline layer)
        "Applications": "#f4886f",       # salmon
        "Tutorials": "#8aa6ac",          # light slate
        "Lists": "#a5bbbe",              # pale slate
        "Misc": "#c9d4d6",               # faint slate
    }
    return C, CAT_COLORS, CHART_LAYOUT, F, LAYOUT


@app.cell(hide_code=True)
def fonts(mo):
    mo.Html(
        '<style>'
        '@import url("https://fonts.googleapis.com/css2?family=DM+Mono:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&family=Noto+Serif:ital,wght@0,400;0,600;1,400&family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap");'
        '</style>'
    )
    return


@app.cell(hide_code=True)
def header(C, F, mo):
    mo.Html(
        f'<div style="padding:40px 0 28px; border-bottom:2px solid {C["accent"]}; margin-bottom:36px;">'
        f'<h1 style="font-family:{F["headline"]}; font-size:2.2rem; font-weight:600; '
        f'color:{C["ink"]}; margin:0 0 14px; line-height:1.05; letter-spacing:-0.025em;">'
        f'Open-Source AI in France</h1>'
        f'<p style="font-family:{F["body"]}; font-size:1rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.5;">'
        f'Surveying 15,000+ active repositories (156K+ developers) across the open-source AI stack. '
        f'This view filters to France-based projects: potential grantees for Pionniers de l’IA.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def load_france_repos(mo, pyoso_db_conn):
    df_france = mo.sql(
        f"""
        SELECT
          repo,
          SPLIT_PART(repo, '/', 1) AS owner,
          SPLIT_PART(repo, '/', 2) AS name,
          category,
          subcategory,
          CAST(stars AS BIGINT) AS stars,
          CAST(contributors AS BIGINT) AS contributors,
          CAST(star_7d AS BIGINT) AS star_7d,
          language
        FROM currentai.scores.repos_summary
        WHERE LOWER(country) = 'france'
        """,
        output=False,
        engine=pyoso_db_conn
    )
    return (df_france,)


@app.cell(hide_code=True)
def load_global_stats(mo, pyoso_db_conn):
    df_global = mo.sql(
        f"""
        SELECT
          COUNT(*) AS total_repos,
          SUM(CAST(contributors AS BIGINT)) AS total_contributors
        FROM currentai.scores.repos_summary
        """,
        output=False,
        engine=pyoso_db_conn
    )
    return (df_global,)


@app.cell(hide_code=True)
def headline_stats(C, F, df_france, df_global, mo):
    _total_repos = int(df_global['total_repos'].iloc[0])
    _total_devs = int(df_global['total_contributors'].iloc[0])
    mo.vstack([
        mo.Html(
            f'<p style="font-family:{F["body"]}; font-size:0.95rem; color:{C["ink_2"]}; '
            f'line-height:1.5; margin:0 0 16px;">'
            f'Across the full survey of <strong>{_total_repos:,} repos</strong> '
            f'and <strong>{_total_devs:,} developers</strong>, '
            f'<strong>{len(df_france)} repositories</strong> are based in France '
            f'spanning <strong>{df_france["category"].nunique()} categories</strong> '
            f'and <strong>{df_france["subcategory"].nunique()} subcategories</strong> '
            f'of the AI stack.</p>'
        ),
        mo.hstack([
            mo.stat(value=len(df_france), label="French Repos", bordered=True, caption="across the AI stack"),
            mo.stat(value=f"{df_france['stars'].sum():,}", label="Total Stars", bordered=True, caption="community adoption"),
            mo.stat(value=f"{df_france['contributors'].sum():,}", label="Contributors", bordered=True, caption="active developers"),
            mo.stat(value=df_france['owner'].nunique(), label="Organizations", bordered=True, caption="unique maintainers"),
            mo.stat(value=df_france['category'].nunique(), label="Stack Layers", bordered=True, caption="of 8 categories covered"),
        ], widths="equal", gap=1),
    ])
    return


@app.cell(hide_code=True)
def section_by_category(C, F, mo):
    mo.Html(
        f'<div style="margin:44px 0 20px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">'
        f'Stack Coverage</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.6rem; font-weight:600;'
        f'color:{C["ink"]}; margin:0 0 8px;">Where does France show up in the AI stack?</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.9rem; color:{C["ink_3"]}; '
        f'margin:0; line-height:1.5;">'
        f'Repository count by GoodAI List category. Color encodes stack layer.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def france_by_category(CAT_COLORS, LAYOUT, C, df_france, go, mo):
    _by_cat = df_france.groupby('category').agg(
        repos=('repo', 'nunique'),
        total_stars=('stars', 'sum'),
        total_contributors=('contributors', 'sum'),
    ).reset_index().sort_values('repos', ascending=True)

    _fig = go.Figure(go.Bar(
        y=_by_cat['category'],
        x=_by_cat['repos'],
        orientation='h',
        marker_color=[CAT_COLORS.get(c, C['ink_3']) for c in _by_cat['category']],
        customdata=list(zip(_by_cat['total_stars'], _by_cat['total_contributors'])),
        hovertemplate="<b>%{y}</b><br>Repos: %{x}<br>Stars: %{customdata[0]:,}<br>Contributors: %{customdata[1]:,}<extra></extra>",
    ))
    _fig.update_layout(
        **LAYOUT,
        height=350,
        xaxis=dict(title='Repositories', showgrid=True, gridcolor=C['rule']),
        yaxis=dict(title='', showgrid=False),
    )
    mo.ui.plotly(_fig, config={"displayModeBar": False})
    return


@app.cell(hide_code=True)
def section_subcategories(C, F, mo):
    mo.Html(
        f'<div style="margin:44px 0 20px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">'
        f'Subcategory Depth</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.6rem; font-weight:600;'
        f'color:{C["ink"]}; margin:0 0 8px;">Which niches are strongest?</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.9rem; color:{C["ink_3"]}; '
        f'margin:0; line-height:1.5;">'
        f'Top 20 subcategories with at least 2 French repos.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def france_by_subcategory(CAT_COLORS, LAYOUT, C, df_france, go, mo):
    _by_sub = df_france.groupby(['category', 'subcategory']).agg(
        repos=('repo', 'nunique'),
        total_stars=('stars', 'sum'),
    ).reset_index()
    _by_sub = _by_sub[_by_sub['repos'] >= 2].sort_values('repos', ascending=True).tail(20)

    _fig = go.Figure(go.Bar(
        y=_by_sub['subcategory'],
        x=_by_sub['repos'],
        orientation='h',
        marker_color=[CAT_COLORS.get(c, C['ink_3']) for c in _by_sub['category']],
        customdata=list(zip(_by_sub['category'], _by_sub['total_stars'])),
        hovertemplate="<b>%{y}</b><br>Category: %{customdata[0]}<br>Repos: %{x}<br>Stars: %{customdata[1]:,}<extra></extra>",
    ))
    _fig.update_layout(
        **LAYOUT,
        height=500,
        xaxis=dict(title='Repositories', showgrid=True, gridcolor=C['rule']),
        yaxis=dict(title='', showgrid=False),
    )
    mo.ui.plotly(_fig, config={"displayModeBar": False})
    return


@app.cell(hide_code=True)
def section_projects(C, F, mo):
    mo.Html(
        f'<div style="margin:44px 0 20px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">'
        f'Top Projects</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.6rem; font-weight:600;'
        f'color:{C["ink"]}; margin:0 0 8px;">Leading French AI repositories</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.9rem; color:{C["ink_3"]}; '
        f'margin:0; line-height:1.5;">'
        f'Top 30 by star count, including Mistral, Hugging Face contributors, Pathway, and more.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def top_french_projects(df_france, mo):
    _top = df_france.nlargest(30, 'stars')[
        ['repo', 'category', 'subcategory', 'stars', 'contributors', 'language']
    ].copy()
    _top['stars'] = _top['stars'].apply(lambda x: f"{x:,}")
    _top.columns = ['Repository', 'Category', 'Subcategory', 'Stars', 'Contributors', 'Language']
    _top = _top.reset_index(drop=True)
    mo.ui.table(_top, show_column_summaries=False, show_data_types=False)
    return


@app.cell(hide_code=True)
def section_orgs(C, F, mo):
    mo.Html(
        f'<div style="margin:44px 0 20px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">'
        f'Organizations</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.6rem; font-weight:600;'
        f'color:{C["ink"]}; margin:0 0 8px;">Potential grantees</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.9rem; color:{C["ink_3"]}; '
        f'margin:0; line-height:1.5;">'
        f'Organizations with the most active AI repositories based in France.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def top_french_orgs(df_france, mo, pd):
    _by_org = df_france.groupby('owner').agg(
        repos=('repo', 'nunique'),
        total_stars=('stars', 'sum'),
        total_contributors=('contributors', 'sum'),
        categories=('category', 'nunique'),
    ).reset_index()
    _by_org = _by_org.nlargest(20, 'total_stars')
    _by_org['total_stars'] = _by_org['total_stars'].apply(lambda x: f"{x:,}")
    _by_org.columns = ['Organization', 'Repos', 'Stars', 'Contributors', 'Categories']
    _by_org = _by_org.reset_index(drop=True)
    mo.ui.table(_by_org, show_column_summaries=False, show_data_types=False)
    return


@app.cell(hide_code=True)
def section_momentum(C, F, mo):
    mo.Html(
        f'<div style="margin:44px 0 20px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">'
        f'Momentum</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.6rem; font-weight:600;'
        f'color:{C["ink"]}; margin:0 0 8px;">What’s trending in France right now?</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.9rem; color:{C["ink_3"]}; '
        f'margin:0; line-height:1.5;">'
        f'French repos with the most stars gained in the last 7 days.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def france_momentum(C, LAYOUT, df_france, go, mo):
    _data = df_france[df_france['star_7d'] > 0].nlargest(15, 'star_7d').sort_values('star_7d', ascending=True)

    if _data.empty:
        _output = mo.md("_No repos with 7-day star growth data._")
    else:
        _fig = go.Figure(go.Bar(
            y=_data['repo'],
            x=_data['star_7d'],
            orientation='h',
            marker_color=C['healthy'],
            customdata=list(zip(_data['category'], _data['stars'])),
            hovertemplate="<b>%{y}</b><br>Category: %{customdata[0]}<br>7d stars: %{x:,}<br>Total stars: %{customdata[1]:,}<extra></extra>",
        ))
        _fig.update_layout(
            **LAYOUT,
            height=420,
            xaxis=dict(title='Stars gained (last 7 days)', showgrid=True, gridcolor=C['rule']),
            yaxis=dict(title='', showgrid=False),
        )
        _output = mo.ui.plotly(_fig, config={"displayModeBar": False})
    _output
    return


@app.cell(hide_code=True)
def section_languages(C, F, mo):
    mo.Html(
        f'<div style="margin:44px 0 20px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">'
        f'Tech Stack</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.6rem; font-weight:600;'
        f'color:{C["ink"]}; margin:0 0 8px;">Primary languages</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.9rem; color:{C["ink_3"]}; '
        f'margin:0; line-height:1.5;">'
        f'Distribution of primary programming languages across French AI repos.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def france_language_breakdown(CAT_COLORS, C, LAYOUT, df_france, go, mo):
    _by_lang = df_france.groupby('language').agg(
        repos=('repo', 'nunique'),
    ).reset_index()
    _by_lang = _by_lang[_by_lang['language'].notna()].nlargest(10, 'repos')
    _by_lang = _by_lang.sort_values('repos', ascending=True)

    # Language is a plain ranking, not a meaningful categorical encoding, so a
    # single brand hue reads cleaner than a rainbow (matches the AI Stack Map).
    _fig = go.Figure(go.Bar(
        y=_by_lang['language'],
        x=_by_lang['repos'],
        orientation='h',
        marker_color=C['accent'],
        hovertemplate="<b>%{y}</b><br>Repos: %{x}<extra></extra>",
    ))
    _fig.update_layout(
        **LAYOUT,
        height=350,
        xaxis=dict(title='Repositories', showgrid=True, gridcolor=C['rule']),
        yaxis=dict(title='', showgrid=False),
    )
    mo.ui.plotly(_fig, config={"displayModeBar": False})
    return


@app.cell(hide_code=True)
def methodology(C, F, mo):
    mo.Html(
        f'<div style="margin-top:44px; padding-top:20px; border-top:1px solid {C["rule"]};">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["ink_3"]}; '
        f'letter-spacing:0.08em; text-transform:uppercase; margin-bottom:8px;">Methodology</div>'
        f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; line-height:1.5;">'
        f'Repos are tagged as "France" by GoodAI List based on the primary maintainer’s '
        f'GitHub profile location. This is a floor: it undercounts French projects where '
        f'the maintainer lists no location or lists a different country. The full survey covers '
        f'15,000+ active AI repositories across 8 categories of the open-source AI stack.</p>'
        f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; margin-top:8px;">'
        f'<strong>Source:</strong> '
        f'<a href="https://www.oso.xyz" style="color:{C["accent"]}">Open Source Observer</a>, '
        f'<a href="https://goodailist.com" style="color:{C["accent"]}">GoodAI List</a></p>'
        f'</div>'
    )
    return


if __name__ == "__main__":
    app.run()
