import marimo

__generated_with = "unknown"
app = marimo.App(width="full")


@app.cell(hide_code=True)
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


@app.cell(hide_code=True)
def imports():
    import pandas as pd
    import plotly.graph_objects as go
    return go, pd


@app.cell(hide_code=True)
def style():
    F = {
        "headline": "'Noto Serif', Georgia, serif",
        "body": "'Plus Jakarta Sans', -apple-system, system-ui, sans-serif",
        "mono": "'DM Mono', ui-monospace, SFMono-Regular, monospace",
    }
    C = {
        "ink": "#0b252f",
        "ink_2": "#272726",
        "ink_3": "#8fa1a4",
        "paper": "#f7f6f6",
        "paper_2": "#f2f1f1",
        "rule": "#edecec",
        "white": "#ffffff",
        "border": "#a5bbbe",
        "healthy": "#e86f57",
        "warm": "#f4886f",
        "signal": "#f8ad99",
        "pale": "#f6cabd",
        "accent": "#0b252f",
        "slate": "#3f5d68",
        "slate_mid": "#5f7e88",
        "slate_lt": "#a5bbbe",
        "slate_faint": "#c9d4d6",
    }
    LAYOUT = dict(
        plot_bgcolor="white",
        paper_bgcolor="white",
        font=dict(family=F["body"], size=12, color=C["ink"]),
        margin=dict(t=64, l=60, r=24, b=50),
        hovermode="closest",
    )
    LAYER_COLORS = {
        "product_ux": "#e86f57",
        "model_components": "#3f5d68",
        "infrastructure": "#a5bbbe",
    }
    LAYER_LABELS = {
        "product_ux": "Product / UX",
        "model_components": "Model components",
        "infrastructure": "Infrastructure",
    }
    return C, F, LAYER_COLORS, LAYER_LABELS, LAYOUT


@app.cell(hide_code=True)
def fonts(mo):
    mo.Html(
        '<style>'
        '@import url("https://fonts.googleapis.com/css2?family=DM+Mono:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&family=Noto+Serif:ital,wght@0,400;0,600;1,400&family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap");'
        '</style>'
    )
    return


@app.cell(hide_code=True)
def header(C, F, mo):
    mo.Html(
        f'<div style="padding:40px 0 28px; border-bottom:2px solid {C["accent"]}; margin-bottom:8px;">'
        f'<h1 style="font-family:{F["headline"]}; font-size:2.3rem; font-weight:600; '
        f'color:{C["ink"]}; margin:0 0 14px; line-height:1.05; letter-spacing:-0.025em;">'
        f'The open source AI stack, in three charts</h1>'
        f'<p style="font-family:{F["body"]}; font-size:1.05rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.55;">'
        f'Three findings from the AI Stack Map, each in one sentence, one paragraph, and one chart.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def kpi_strip(df_contrib, df_tiers, mo):
    _core = int(df_tiers["core"].iloc[0])
    _any_oc = int(df_tiers["any_excl_oc"].iloc[0])
    _repos = df_contrib["repo"].nunique()
    _multi = (df_contrib.groupby("developer_id")["repo"].nunique() >= 2).sum()
    mo.hstack([
        mo.stat(label="Contributors", value=f"{_any_oc:,}", bordered=True, caption="distinct, last 12 months"),
        mo.stat(label="Core contributors", value=f"{_core:,}", bordered=True, caption="50+ commits, last 12 months"),
        mo.stat(label="Multi-project developers", value=f"{int(_multi):,}", bordered=True, caption="contribute to 2+ open projects"),
        mo.stat(label="Open projects", value=f"{_repos:,}", bordered=True, caption="scored across the stack"),
    ], widths="equal", gap=1)
    return


@app.cell(hide_code=True)
def s_people(C, F, mo):
    mo.Html(
        f'<div style="margin:48px 0 18px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">People</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.7rem; font-weight:600; '
        f'color:{C["ink"]}; margin:0 0 10px; letter-spacing:-0.015em;">'
        f'Open source AI is built by one connected community, not a set of silos.</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.98rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.6;">'
        f'Tens of thousands of developers committed code to the open source AI stack in the last year. Even the core, '
        f'those with 50 or more commits, is comparable to the combined disclosed headcount of every major closed '
        f'lab. The network below links two projects whenever they share contributors. The dense center shows the '
        f'same developers working across projects and across layers, which is what makes the ecosystem hard to '
        f'fork or capture. Pick any project below to trace who it shares contributors with.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def c_people(C, F, LAYER_COLORS, LAYER_LABELS, df_contrib, mo):
    import json as _json
    import html as _html
    from itertools import combinations
    from collections import Counter

    _agg = (df_contrib.groupby("repo")
            .agg(contributors=("developer_id", "nunique"),
                 layer=("layer", "first"),
                 product=("product_name", "first")))
    _cand = _agg[_agg["contributors"] >= 8]
    _cand_set = set(_cand.index)

    _dev_repos = (df_contrib[df_contrib["repo"].isin(_cand_set)]
                  .groupby("developer_id")["repo"].apply(lambda s: sorted(set(s))))
    _ec = Counter()
    for _rs in _dev_repos:
        if 1 < len(_rs) <= 40:
            for _a, _b in combinations(_rs, 2):
                _ec[(_a, _b)] += 1
    _pairs = [(a, b, w) for (a, b), w in _ec.items() if w >= 5]

    _conn = set()
    for _a, _b, _w in _pairs:
        _conn.add(_a)
        _conn.add(_b)
    _nodes_df = (_cand[_cand.index.isin(_conn)].reset_index()
                 .nlargest(80, "contributors").reset_index(drop=True))
    _keep = set(_nodes_df["repo"])
    _hubs = set(_nodes_df.nlargest(12, "contributors")["repo"])

    _nodes = [{
        "id": _r["repo"], "name": _r["product"], "layer": _r["layer"],
        "contributors": int(_r["contributors"]),
        "r": float(min(26.0, (_r["contributors"] ** 0.5) * 0.55 + 5)),
        "color": LAYER_COLORS.get(_r["layer"], C["ink_3"]),
        "hub": bool(_r["repo"] in _hubs),
    } for _, _r in _nodes_df.iterrows()]
    _links = [{"source": a, "target": b, "weight": int(w)}
              for a, b, w in _pairs if a in _keep and b in _keep]
    _cfg = {
        "nodes": _nodes, "links": _links, "height": 600,
        "edge": C["slate_lt"], "ink": C["ink"],
        "legend": [{"label": LAYER_LABELS[_lk], "color": _lv} for _lk, _lv in LAYER_COLORS.items()],
    }
    _cfg_js = _json.dumps(_cfg).replace("</", "<\\/")

    _head = (
        '<!DOCTYPE html><html><head><meta charset="utf-8">'
        '<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>'
        '<style>'
        "@import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&display=swap');"
        '*{margin:0;box-sizing:border-box}'
        'html,body{background:#fff;overflow:hidden;height:100%;font-family:"DM Mono",monospace}'
        '#bar{display:flex;align-items:center;gap:10px;padding:8px 4px 4px;font-size:11px;color:#0b252f}'
        '#bar select{font-family:"DM Mono",monospace;font-size:12px;color:#0b252f;background:#fff;'
        'border:1px solid #a5bbbe;border-radius:0;padding:5px 9px;outline:none;max-width:300px}'
        '#legend{margin-left:auto;text-transform:uppercase;letter-spacing:0.04em}'
        '.leg{display:inline-flex;align-items:center;margin-left:16px}'
        '.leg i{width:9px;height:9px;border-radius:50%;display:inline-block;margin-right:6px}'
        'text{font-family:"DM Mono",monospace}'
        '</style></head><body>'
        '<div id="bar"><span>Focus project</span><select id="focus"></select>'
        '<span id="legend"></span></div><div id="chart"></div>'
        '<script>'
    )
    _js = """
    const CFG = window.__CFG__;
    const AN = CFG.nodes, AL = CFG.links;
    const adj = {};
    AN.forEach(function(n){ adj[n.id] = new Set([n.id]); });
    AL.forEach(function(l){ adj[l.source].add(l.target); adj[l.target].add(l.source); });
    document.getElementById('legend').innerHTML = CFG.legend.map(function(d){
        return '<span class="leg"><i style="background:'+d.color+'"></i>'+d.label+'</span>'; }).join('');
    const byC = AN.slice().sort(function(a,b){ return b.contributors-a.contributors; });
    const focusEl = document.getElementById('focus');
    focusEl.innerHTML = '<option value="__all__">All projects</option>' + byC.map(function(n){
        return '<option value="'+n.id+'">'+n.name+'</option>'; }).join('');
    focusEl.value = '__all__';

    const el = document.getElementById('chart');
    const W = el.clientWidth || 900, H = CFG.height;
    const svg = d3.select('#chart').append('svg').attr('width','100%').attr('height',H).attr('viewBox','0 0 '+W+' '+H);
    const root = svg.append('g');
    svg.call(d3.zoom().scaleExtent([0.3,4]).on('zoom', function(e){ root.attr('transform', e.transform); }));
    let sim = null;
    function eid(x){ return (x && x.id) ? x.id : x; }
    function draw(focus){
        const keep = (focus==='__all__') ? null : adj[focus];
        const nodes = AN.filter(function(n){ return !keep || keep.has(n.id); }).map(function(d){ return Object.assign({}, d); });
        const links = AL.filter(function(l){ return !keep || (keep.has(eid(l.source)) && keep.has(eid(l.target))); })
            .map(function(l){ return {source:eid(l.source), target:eid(l.target), weight:l.weight}; });
        if(sim) sim.stop();
        root.selectAll('*').remove();
        sim = d3.forceSimulation(nodes)
            .force('link', d3.forceLink(links).id(function(d){ return d.id; })
                .distance(function(d){ return 120/Math.sqrt(d.weight)+34; })
                .strength(function(d){ return Math.min(0.7, d.weight/24); }))
            .force('charge', d3.forceManyBody().strength(focus==='__all__' ? -520 : -560).distanceMax(W))
            .force('x', d3.forceX(W/2).strength(0.05))
            .force('y', d3.forceY(H/2).strength(0.13))
            .force('collide', d3.forceCollide().radius(function(d){ return d.r+8; }));
        const link = root.append('g').attr('stroke', CFG.edge).attr('stroke-opacity', 0.45)
            .selectAll('line').data(links).join('line')
            .attr('stroke-width', function(d){ return Math.sqrt(d.weight)*0.5+0.4; });
        const node = root.append('g').selectAll('circle').data(nodes).join('circle')
            .attr('r', function(d){ return d.r; }).attr('fill', function(d){ return d.color; })
            .attr('stroke', function(d){ return d.id===focus ? CFG.ink : '#fff'; })
            .attr('stroke-width', function(d){ return d.id===focus ? 2.5 : 1.2; })
            .style('cursor','pointer')
            .call(d3.drag().on('start', ds).on('drag', dg).on('end', de));
        node.append('title').text(function(d){ return d.name+': '+d.contributors.toLocaleString()+' contributors'; });
        const labelData = (focus==='__all__') ? nodes.filter(function(d){ return d.hub; }) : nodes;
        const label = root.append('g').selectAll('text').data(labelData).join('text')
            .text(function(d){ return d.name; }).attr('font-size', 10).attr('fill', CFG.ink)
            .attr('text-anchor','middle').attr('pointer-events','none').attr('paint-order','stroke')
            .attr('stroke','#fff').attr('stroke-width',3).attr('stroke-linejoin','round');
        sim.on('tick', function(){
            link.attr('x1', function(d){ return d.source.x; }).attr('y1', function(d){ return d.source.y; })
                .attr('x2', function(d){ return d.target.x; }).attr('y2', function(d){ return d.target.y; });
            node.attr('cx', function(d){ return d.x; }).attr('cy', function(d){ return d.y; });
            label.attr('x', function(d){ return d.x; }).attr('y', function(d){ return d.y-d.r-5; });
        });
        node.on('mouseover', function(e,d){
            node.attr('opacity', function(n){ return adj[d.id].has(n.id) ? 1 : 0.12; });
            link.attr('stroke-opacity', function(l){ return (eid(l.source)===d.id || eid(l.target)===d.id) ? 0.85 : 0.05; });
            label.attr('opacity', function(n){ return adj[d.id].has(n.id) ? 1 : 0.12; });
        }).on('mouseout', function(){ node.attr('opacity',1); link.attr('stroke-opacity',0.45); label.attr('opacity',1); });
    }
    function ds(e){ if(!e.active) sim.alphaTarget(0.3).restart(); e.subject.fx=e.subject.x; e.subject.fy=e.subject.y; }
    function dg(e){ e.subject.fx=e.x; e.subject.fy=e.y; }
    function de(e){ if(!e.active) sim.alphaTarget(0); e.subject.fx=null; e.subject.fy=null; }
    focusEl.addEventListener('change', function(){ draw(focusEl.value); });
    draw(focusEl.value);
    """
    _inner = _head + "window.__CFG__=" + _cfg_js + ";" + _js + "</script></body></html>"
    _src = _html.escape(_inner, quote=True)
    mo.Html(
        '<div style="font-family:' + F["headline"] + ';font-size:15px;color:' + C["ink"]
        + ';margin:0 0 2px;">The open source AI stack, linked where projects share contributors</div>'
        '<div style="font-family:' + F["mono"] + ';font-size:11px;color:' + C["ink_3"]
        + ';margin:0 0 6px;">Pick a project to see who it shares contributors with. Drag, scroll to zoom, hover to isolate.</div>'
        '<iframe srcdoc="' + _src + '" style="width:100%;height:690px;border:none;" scrolling="no"></iframe>'
    )
    return


@app.cell(hide_code=True)
def s_categories(C, F, mo):
    mo.Html(
        f'<div style="margin:48px 0 18px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">Categories</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.7rem; font-weight:600; '
        f'color:{C["ink"]}; margin:0 0 10px; letter-spacing:-0.015em;">'
        f'The fastest-growing category in open source AI didn\'t exist 18 months ago.</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.98rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.6;">'
        f'The agent-tooling layer barely existed before late 2024. An open standard, MCP, catalyzed it, and '
        f'almost every project in the category has been created since. The framework core, by contrast, has '
        f'added no new open entrants since 2024. Breakout open products and standards keep creating new '
        f'categories, and the map adds rows to track them.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def c_categories(C, F, LAYER_COLORS, LAYOUT, df_founding, go, mo, pd):
    _df = df_founding.copy()
    _df["created_at"] = pd.to_datetime(_df["created_at"])
    _df = _df[_df["created_at"] >= "2014-01-01"]
    _df["month"] = _df["created_at"].values.astype("datetime64[M]")
    _counts = _df.groupby(["month", "category"]).size().unstack(fill_value=0)
    _grid = pd.date_range(_counts.index.min(), _counts.index.max(), freq="MS")
    _counts = _counts.reindex(_grid, fill_value=0).cumsum()
    _cat_layer = _df.drop_duplicates("category").set_index("category")["layer"].to_dict()
    _finals = _counts.iloc[-1].sort_values(ascending=False)
    _order = _finals.index.tolist()
    # Dodge end labels downward so none collide, even when two categories end
    # on the same value (e.g. Deployment and Evaluation Code both at 11).
    _gap = float(_finals.max()) * 0.035
    _label_y, _prev = {}, None
    for _cat in _order:
        _y = float(_finals[_cat])
        if _prev is not None and _prev - _y < _gap:
            _y = _prev - _gap
        _label_y[_cat] = _y
        _prev = _y
    _fig = go.Figure()
    for _cat in _order:
        _color = LAYER_COLORS.get(_cat_layer.get(_cat), C["ink_3"])
        _fig.add_trace(go.Scatter(
            x=_counts.index, y=_counts[_cat], mode="lines",
            line=dict(color=_color, width=2), showlegend=False,
            hovertemplate="<b>" + _cat + "</b><br>%{x|%b %Y}: %{y} projects<extra></extra>",
        ))
        _fig.add_annotation(
            x=_counts.index[-1], y=_label_y[_cat], text="  " + _cat,
            xanchor="left", yanchor="middle", showarrow=False,
            font=dict(family=F["mono"], size=9, color=_color),
        )
    _fig.update_layout(**LAYOUT, height=560)
    _fig.update_layout(
        title=dict(text="Cumulative open source projects founded, by category",
                   font=dict(family=F["headline"], size=15, color=C["ink"]), x=0, xref="paper"),
        margin=dict(t=64, l=60, r=230, b=50),
    )
    _fig.update_xaxes(title="", showgrid=False, showline=True, linecolor=C["ink"],
                      tickfont=dict(size=11, color=C["ink_3"]))
    _fig.update_yaxes(title="Cumulative projects", showgrid=True, gridcolor=C["rule"],
                      rangemode="tozero", showline=True, linecolor=C["ink"], zeroline=False,
                      tickfont=dict(size=11, color=C["ink_3"]))
    mo.ui.plotly(_fig, config={"displayModeBar": False})
    return


@app.cell(hide_code=True)
def s_resilience(C, F, mo):
    mo.Html(
        f'<div style="margin:48px 0 18px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">Resilience</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.7rem; font-weight:600; '
        f'color:{C["ink"]}; margin:0 0 10px; letter-spacing:-0.015em;">'
        f'Most open projects spread the work; a few widely-used tools rest on one person.</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.98rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.6;">'
        f'Each dot is one of the 50 most-active open source AI projects, placed by how mature it is (vertical) '
        f'against how much of its code comes from a single top contributor (horizontal). The healthy pattern '
        f'fills the upper left: large projects like vLLM, SGLang, and Transformers where the busiest contributor '
        f'writes under 3% of commits. The concern is the upper right, where widely-used tools lean on very few '
        f'shoulders. TensorFlow is the standout, a mature project with nearly a third of its recent commits from '
        f'one author, alongside a cluster of evaluation and agent tools such as promptfoo, Unsloth, and Inspect AI.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def c_resilience(C, F, LAYOUT, df_contrib, go, mo):
    _src = df_contrib[df_contrib["repo"] != "openclaw/openclaw"]
    _d = (_src.groupby("repo").agg(
        product=("product_name", "first"), maturity=("maturity", "first"),
        contributors=("developer_id", "nunique"), total=("commits_12mo", "sum"),
        top1=("commits_12mo", "max")).reset_index())
    _d = _d[_d["maturity"].notna() & (_d["total"] > 0)]
    _d["top1_share"] = 100.0 * _d["top1"] / _d["total"]
    # Sample the 50 projects the ecosystem leans on most (by contributor count).
    _d = _d.nlargest(50, "contributors")
    _XT, _YT = 15.0, 4.0  # concentration / maturity thresholds
    _danger = (_d["maturity"] >= _YT) & (_d["top1_share"] >= _XT)
    _xmax = float(_d["top1_share"].max()) * 1.12

    _fig = go.Figure()
    # Shade the at-risk quadrant: widely used and concentrated.
    _fig.add_shape(type="rect", x0=_XT, x1=_xmax, y0=_YT, y1=5.35,
                   fillcolor=C["healthy"], opacity=0.06, line_width=0, layer="below")
    _fig.add_hline(y=_YT, line=dict(color=C["slate_faint"], width=1, dash="dot"))
    _fig.add_vline(x=_XT, line=dict(color=C["slate_faint"], width=1, dash="dot"))
    _fig.add_trace(go.Scatter(
        x=_d["top1_share"], y=_d["maturity"], mode="markers",
        marker=dict(size=9 + (_d["contributors"] ** 0.5) * 0.32, opacity=0.85,
                    color=[C["healthy"] if _b else C["slate_lt"] for _b in _danger],
                    line=dict(width=1, color="white")),
        customdata=list(zip(_d["product"], _d["contributors"])),
        hovertemplate="<b>%{customdata[0]}</b><br>Top contributor: %{x:.1f}% of commits<br>"
                      "Maturity: %{y}<br>Contributors: %{customdata[1]:,}<extra></extra>",
        showlegend=False,
    ))
    # Label the standout at-risk projects, with hand-tuned offsets so the
    # tight y=4 cluster (Unsloth, promptfoo, LightRAG) does not collide.
    _label = {
        "TensorFlow": ("left", "bottom", 6, 2),
        "Inspect AI": ("left", "bottom", 6, 2),
        "LibreChat": ("left", "top", 6, -3),
        "Unsloth": ("right", "middle", -6, 0),
        "promptfoo": ("center", "bottom", 0, 9),
        "LightRAG": ("left", "bottom", 6, 2),
    }
    for _, _r in _d[_danger].iterrows():
        _o = _label.get(_r["product"])
        if _o:
            _fig.add_annotation(x=_r["top1_share"], y=_r["maturity"], text=_r["product"],
                                xanchor=_o[0], yanchor=_o[1], xshift=_o[2], yshift=_o[3],
                                showarrow=False, font=dict(family=F["mono"], size=9, color=C["ink"]))
    _fig.update_layout(**LAYOUT, height=560)
    _fig.update_layout(
        title=dict(text="Maturity vs. reliance on a single contributor (50 most-active open projects)",
                   font=dict(family=F["headline"], size=15, color=C["ink"]), x=0, xref="paper"),
    )
    _fig.add_annotation(x=0.99, y=0.04, xref="paper", yref="paper", showarrow=False, align="right",
                        text="Salmon = widely used, and one author writes 15%+ of commits",
                        font=dict(family=F["mono"], size=11, color=C["healthy"]))
    _fig.update_xaxes(title="Top contributor's share of commits (%)", showgrid=True, gridcolor=C["rule"],
                      showline=True, linecolor=C["ink"], rangemode="tozero", range=[0, _xmax],
                      tickfont=dict(size=11, color=C["ink_3"]))
    _fig.update_yaxes(title="Maturity score (adoption x capability)", showgrid=True, gridcolor=C["rule"],
                      showline=True, linecolor=C["ink"], range=[float(_d["maturity"].min()) - 0.4, 5.4],
                      tickfont=dict(size=11, color=C["ink_3"]))
    mo.ui.plotly(_fig, config={"displayModeBar": False})
    return


@app.cell(hide_code=True)
def methodology(C, F, mo):
    mo.Html(
        f'<div style="margin-top:52px; padding-top:20px; border-top:1px solid {C["rule"]};">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["ink_3"]}; '
        f'letter-spacing:0.08em; text-transform:uppercase; margin-bottom:8px;">Methodology</div>'
        f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; line-height:1.55;">'
        f'Contributors are distinct GitHub code committers (bots excluded) to the scored open-stack repositories '
        f'over the trailing 12 months, from <span style="font-family:{F["mono"]};font-size:0.9em;">'
        f'currentai.scores.stack_contributors</span> joined to the taxonomy bridge '
        f'<span style="font-family:{F["mono"]};font-size:0.9em;">currentai.catalog.stack_map</span>. '
        f'The network links two projects when they share 4 or more contributors; node size is contributor '
        f'count and color is stack layer. Founding date is repo '
        f'<span style="font-family:{F["mono"]};font-size:0.9em;">created_at</span>. Resilience plots the 50 open '
        f'projects with the most contributors, placing maturity (the adoption x capability blend from the AI '
        f'Stack Map gap engine, carried on the bridge) against the share of commits written by each project\'s '
        f'single most active contributor; the viral 2025 outlier OpenClaw is excluded. Underlying data: OSO and '
        f'GitHub Archive.</p>'
        f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; margin-top:8px;">'
        f'<strong>Source:</strong> '
        f'<a href="https://www.oso.xyz" style="color:{C["accent"]}">OSO</a>, '
        f'<a href="https://map.currentai.org" style="color:{C["accent"]}">AI Stack Map</a></p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def load_contrib(mo, pyoso_db_conn):
    df_contrib = mo.sql(
        """
        SELECT sc.developer_id, sc.repo, sc.product_name, sc.layer, sc.commits_12mo,
               sm.maturity
        FROM currentai.scores.stack_contributors sc
        JOIN currentai.catalog.stack_map sm ON sc.repo = sm.repo
        WHERE sc.openness_bucket IN ('open', 'open-ish')
        """,
        output=False, engine=pyoso_db_conn,
    )
    return (df_contrib,)


@app.cell(hide_code=True)
def load_tiers(mo, pyoso_db_conn):
    df_tiers = mo.sql(
        """
        WITH dev AS (
          SELECT developer_id, SUM(commits_12mo) AS commits
          FROM currentai.scores.stack_contributors
          WHERE openness_bucket IN ('open', 'open-ish') AND repo <> 'openclaw/openclaw'
          GROUP BY developer_id
        )
        SELECT
          (SELECT COUNT(*) FROM dev) AS any_excl_oc,
          (SELECT COUNT(*) FROM dev WHERE commits >= 50) AS core
        """,
        output=False, engine=pyoso_db_conn,
    )
    return (df_tiers,)


@app.cell(hide_code=True)
def load_founding(mo, pyoso_db_conn):
    df_founding = mo.sql(
        """
        SELECT c.category_name AS category, s.layer, r.created_at
        FROM currentai.entities.repos r
        JOIN currentai.catalog.stack_map s ON LOWER(r.repo) = s.repo
        JOIN currentai.stack_map.categories c ON c.category_id = s.category
        WHERE s.openness_bucket IN ('open', 'open-ish') AND r.created_at IS NOT NULL
        """,
        output=False, engine=pyoso_db_conn,
    )
    return (df_founding,)


if __name__ == "__main__":
    app.run()
