import marimo

__generated_with = "unknown"
app = marimo.App(width="full")


@app.cell(hide_code=True)
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


@app.cell(hide_code=True)
def imports():
    import pandas as pd
    import plotly.graph_objects as go
    return go, pd


@app.cell(hide_code=True)
def style():
    F = {
        "headline": "'Noto Serif', Georgia, serif",
        "body": "'Plus Jakarta Sans', -apple-system, system-ui, sans-serif",
        "mono": "'DM Mono', ui-monospace, SFMono-Regular, monospace",
    }
    C = {
        "ink": "#0b252f",
        "ink_2": "#272726",
        "ink_3": "#8fa1a4",
        "paper": "#f7f6f6",
        "paper_2": "#f2f1f1",
        "rule": "#edecec",
        "white": "#ffffff",
        "border": "#a5bbbe",
        # Brand salmon ramp: deep = emphasis, fading to pale coral.
        "healthy": "#e86f57",
        "warm": "#f4886f",
        "signal": "#f8ad99",
        "pale": "#f6cabd",
        # Navy accent + cool slate pair for magnitude/secondary series.
        "accent": "#0b252f",
        "slate": "#3f5d68",
        "slate_mid": "#5f7e88",
        "slate_lt": "#a5bbbe",
        "slate_faint": "#c9d4d6",
    }
    LAYOUT = dict(
        plot_bgcolor="white",
        paper_bgcolor="white",
        font=dict(family=F["body"], size=12, color=C["ink"]),
        margin=dict(t=64, l=60, r=24, b=50),
        hovermode="closest",
    )
    # Columbia ontology layers -> brand colors (salmon for the surging app layer).
    LAYER_COLORS = {
        "product_ux": "#e86f57",       # deep salmon
        "model_components": "#3f5d68",  # dark slate
        "infrastructure": "#a5bbbe",    # pale slate
    }
    LAYER_LABELS = {
        "product_ux": "Product / UX",
        "model_components": "Model components",
        "infrastructure": "Infrastructure",
    }
    return C, F, LAYER_COLORS, LAYER_LABELS, LAYOUT


@app.cell(hide_code=True)
def fonts(mo):
    mo.Html(
        '<style>'
        '@import url("https://fonts.googleapis.com/css2?family=DM+Mono:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&family=Noto+Serif:ital,wght@0,400;0,600;1,400&family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap");'
        '</style>'
    )
    return


@app.cell(hide_code=True)
def header(C, F, mo):
    mo.Html(
        f'<div style="padding:40px 0 28px; border-bottom:2px solid {C["accent"]}; margin-bottom:8px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.12em; text-transform:uppercase; margin-bottom:10px;">Current AI</div>'
        f'<h1 style="font-family:{F["headline"]}; font-size:2.3rem; font-weight:600; '
        f'color:{C["ink"]}; margin:0 0 14px; line-height:1.05; letter-spacing:-0.025em;">'
        f'The open-source AI stack, in five charts</h1>'
        f'<p style="font-family:{F["body"]}; font-size:1.05rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.55;">'
        f'Five findings from the AI Stack Map, each in one sentence, one paragraph, and one chart. '
        f'Every number is queried live from the '
        f'<span style="font-family:{F["mono"]}; font-size:0.85em;">currentai</span> warehouse.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def kpi_strip(df_growth, df_inf, df_geo, df_tiers, mo):
    _core = int(df_tiers["core"].iloc[0])
    _countries = int((df_geo["country"] != "Unknown").sum())
    _top3 = df_inf.nlargest(3, "contributors")["contributors"].sum()
    _inf_total = df_inf["contributors"].sum()
    _top3_share = 100.0 * _top3 / _inf_total if _inf_total else 0
    _piv = df_growth.groupby("month")["active_contributors"].sum().sort_index()
    _yoy = 100.0 * (_piv.iloc[-1] - _piv.iloc[0]) / _piv.iloc[0] if len(_piv) > 1 and _piv.iloc[0] else 0
    mo.hstack([
        mo.stat(label="Core contributors", value=f"{_core:,}", bordered=True, caption="≥50 commits to open AI, 12mo"),
        mo.stat(label="Countries", value=str(_countries), bordered=True, caption="where the open stack is built"),
        mo.stat(label="Contributor growth", value=f"+{_yoy:.0f}%", bordered=True, caption="active devs, YoY"),
        mo.stat(label="Inference concentration", value=f"{_top3_share:.0f}%", bordered=True, caption="of contributors on top 3 projects"),
    ], widths="equal", gap=1)
    return


@app.cell(hide_code=True)
def s1(C, F, mo):
    mo.Html(
        f'<div style="margin:48px 0 18px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">Resilience</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.7rem; font-weight:600; '
        f'color:{C["ink"]}; margin:0 0 10px; letter-spacing:-0.015em;">'
        f'A whole layer of open AI runs on three projects.</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.98rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.6;">'
        f'The map rates open inference a "Competitive Open Ecosystem," but its contributor base is narrow. '
        f'vLLM, SGLang, and llama.cpp account for more than four in five of the layer\'s developers. '
        f'Each project is well staffed on its own. The risk is that the whole category depends on so few of them.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def c1(C, F, LAYOUT, df_inf, go, mo):
    _df = df_inf.sort_values("contributors", ascending=True).copy()
    _df["short"] = _df["repo"].apply(lambda r: r.split("/")[-1])
    _rank = _df["contributors"].rank(ascending=False)
    _colors = [C["healthy"] if r <= 3 else C["slate_lt"] for r in _rank]
    _fig = go.Figure(go.Bar(
        x=_df["contributors"], y=_df["short"], orientation="h",
        marker_color=_colors,
        customdata=_df["repo"],
        hovertemplate="<b>%{customdata}</b><br>Contributors (12mo): %{x:,}<extra></extra>",
    ))
    _fig.update_layout(**LAYOUT, height=440)
    _fig.update_layout(
        title=dict(text="Distinct contributors to open inference projects (last 12 months)",
                   font=dict(family=F["headline"], size=15, color=C["ink"]), x=0, xref="paper"),
    )
    _fig.update_xaxes(title="", showgrid=True, gridcolor=C["rule"], tickformat=",d",
                      showline=True, linecolor=C["ink"], tickfont=dict(size=11, color=C["ink_3"]))
    _fig.update_yaxes(title="", showgrid=False, tickfont=dict(size=11, color=C["ink"]))
    mo.ui.plotly(_fig, config={"displayModeBar": False})
    return


@app.cell(hide_code=True)
def s2(C, F, mo):
    mo.Html(
        f'<div style="margin:48px 0 18px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">Geography</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.7rem; font-weight:600; '
        f'color:{C["ink"]}; margin:0 0 10px; letter-spacing:-0.015em;">'
        f'Open AI is built in 16 countries. The closed frontier fits in three.</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.98rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.6;">'
        f'The scored open-stack projects are based in 16 countries. The US leads, followed by China, Germany, '
        f'the UK, Japan, France, Switzerland, India, Israel, Brazil, and Singapore. The major closed labs are '
        f'based in three: the US, the UK (DeepMind), and France (Mistral).</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def c2(C, F, LAYOUT, df_geo, go, mo):
    _df = df_geo[df_geo["country"] != "Unknown"].nlargest(12, "repos").sort_values("repos", ascending=True).copy()
    _colors = [C["healthy"] if c == "USA" else C["slate"] for c in _df["country"]]
    _fig = go.Figure(go.Bar(
        x=_df["repos"], y=_df["country"], orientation="h",
        marker_color=_colors,
        hovertemplate="<b>%{y}</b><br>Open-stack projects: %{x}<extra></extra>",
    ))
    _fig.update_layout(**LAYOUT, height=440)
    _fig.update_layout(
        title=dict(text="Open-stack projects by country (16 countries represented)",
                   font=dict(family=F["headline"], size=15, color=C["ink"]), x=0, xref="paper"),
    )
    _fig.add_annotation(
        x=0.98, y=0.06, xref="paper", yref="paper", showarrow=False, align="right",
        text="Closed frontier labs: ~3 countries<br>(US, UK, France)",
        font=dict(family=F["mono"], size=11, color=C["ink_3"]),
    )
    _fig.update_xaxes(title="", showgrid=True, gridcolor=C["rule"], tickformat=",d",
                      showline=True, linecolor=C["ink"], tickfont=dict(size=11, color=C["ink_3"]))
    _fig.update_yaxes(title="", showgrid=False, tickfont=dict(size=11, color=C["ink"]))
    mo.ui.plotly(_fig, config={"displayModeBar": False})
    return


@app.cell(hide_code=True)
def s3(C, F, mo):
    mo.Html(
        f'<div style="margin:48px 0 18px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">People</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.7rem; font-weight:600; '
        f'color:{C["ink"]}; margin:0 0 10px; letter-spacing:-0.015em;">'
        f'More people build open AI than work at every frontier lab combined.</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.98rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.6;">'
        f'In the last 12 months, tens of thousands of distinct developers committed code to the open AI stack. '
        f'Even the conservative core, those with 50 or more commits in the year, is comparable to the combined '
        f'disclosed headcount of every major closed lab. The broad community is several times larger. '
        f'The comparison is rough: the open figure counts GitHub committers, while the closed figure is a public '
        f'estimate of total employees, not just researchers. Read it as an order-of-magnitude contrast.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def c3(C, F, LAYOUT, df_tiers, go, mo):
    _any = int(df_tiers["any_commit"].iloc[0])
    _any_oc = int(df_tiers["any_excl_oc"].iloc[0])
    _sub = int(df_tiers["substantial"].iloc[0])
    _core = int(df_tiers["core"].iloc[0])
    # Closed-lab combined headcount: rough public estimates of total employees (not just technical).
    _labs_est = 11000
    _rows = [
        ("Open, any contributor", _any, C["pale"], f"{_any:,} ({_any_oc:,} excl. one viral outlier)"),
        ("Open, 10+ commits", _sub, C["warm"], f"{_sub:,}"),
        ("Open, 50+ commits (core)", _core, C["healthy"], f"{_core:,}"),
        ("All frontier labs combined (est.)", _labs_est, C["slate"], "≈11,000 employees (public estimate)"),
    ]
    _labels = [r[0] for r in _rows][::-1]
    _vals = [r[1] for r in _rows][::-1]
    _cols = [r[2] for r in _rows][::-1]
    _txt = [r[3] for r in _rows][::-1]
    _fig = go.Figure(go.Bar(
        x=_vals, y=_labels, orientation="h", marker_color=_cols,
        text=_txt, textposition="outside",
        textfont=dict(family=F["mono"], size=11, color=C["ink"]),
        hovertemplate="<b>%{y}</b><br>%{x:,}<extra></extra>",
    ))
    _fig.update_layout(**LAYOUT, height=420)
    _fig.update_layout(
        title=dict(text="Developers building open AI (12mo) vs. closed-lab headcount",
                   font=dict(family=F["headline"], size=15, color=C["ink"]), x=0, xref="paper"),
    )
    _fig.update_xaxes(title="", showgrid=True, gridcolor=C["rule"], tickformat=",d", range=[0, _any * 1.18],
                      showline=True, linecolor=C["ink"], tickfont=dict(size=11, color=C["ink_3"]))
    _fig.update_yaxes(title="", showgrid=False, tickfont=dict(size=11, color=C["ink"]))
    mo.ui.plotly(_fig, config={"displayModeBar": False})
    return


@app.cell(hide_code=True)
def s4(C, F, mo):
    mo.Html(
        f'<div style="margin:48px 0 18px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">Growth</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.7rem; font-weight:600; '
        f'color:{C["ink"]}; margin:0 0 10px; letter-spacing:-0.015em;">'
        f'The open-AI workforce is growing fast, and moving up the stack.</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.98rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.6;">'
        f'Monthly active contributors to the open stack are up about 80% year-over-year. The growth is uneven by '
        f'layer. The mature infrastructure core is flat, the model layer roughly doubled, and the product and '
        f'agent layer grew fastest. Contribution is concentrating higher up the stack, toward applications and '
        f'agents. The trend excludes one viral 2025 project, OpenClaw, so the figure is not a single-project artifact.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def c4(C, F, LAYER_COLORS, LAYER_LABELS, LAYOUT, df_growth, go, mo, pd):
    _df = df_growth.copy()
    _df["month"] = pd.to_datetime(_df["month"])
    _fig = go.Figure()
    for _layer in ["infrastructure", "model_components", "product_ux"]:
        _d = _df[_df["layer"] == _layer].sort_values("month")
        _fig.add_trace(go.Scatter(
            x=_d["month"], y=_d["active_contributors"],
            name=LAYER_LABELS[_layer], mode="lines",
            line=dict(color=LAYER_COLORS[_layer], width=2.5),
            stackgroup="one",
            hovertemplate="<b>" + LAYER_LABELS[_layer] + "</b><br>%{x|%b %Y}: %{y:,}<extra></extra>",
        ))
    _fig.update_layout(**LAYOUT, height=460)
    _fig.update_layout(
        title=dict(text="Monthly active contributors to the open stack, by layer",
                   font=dict(family=F["headline"], size=15, color=C["ink"]), x=0, xref="paper"),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0,
                    font=dict(size=11), bgcolor="rgba(0,0,0,0)"),
    )
    _fig.update_xaxes(title="", showgrid=False, showline=True, linecolor=C["ink"],
                      tickfont=dict(size=11, color=C["ink_3"]))
    _fig.update_yaxes(title="Active contributors", showgrid=True, gridcolor=C["rule"], tickformat=",d",
                      showline=True, linecolor=C["ink"], tickfont=dict(size=11, color=C["ink_3"]))
    mo.ui.plotly(_fig, config={"displayModeBar": False})
    return


@app.cell(hide_code=True)
def s5(C, F, mo):
    mo.Html(
        f'<div style="margin:48px 0 18px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">Categories</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.7rem; font-weight:600; '
        f'color:{C["ink"]}; margin:0 0 10px; letter-spacing:-0.015em;">'
        f'The fastest-growing category in open AI didn\'t exist 18 months ago.</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.98rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.6;">'
        f'The agent-tooling layer barely existed before late 2024. An open standard, MCP, catalyzed it, and '
        f'almost every project in the category has been created since. The framework core, by contrast, has '
        f'added no new open entrants since 2024. Breakout open products and standards keep creating new '
        f'categories, and the map adds rows to track them.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def c5(C, F, LAYER_COLORS, LAYOUT, df_founding, go, mo, pd):
    _df = df_founding.copy()
    _df["created_at"] = pd.to_datetime(_df["created_at"])
    _df = _df[_df["created_at"] >= "2014-01-01"]
    _df["month"] = _df["created_at"].values.astype("datetime64[M]")
    _counts = _df.groupby(["month", "category"]).size().unstack(fill_value=0)
    _grid = pd.date_range(_counts.index.min(), _counts.index.max(), freq="MS")
    _counts = _counts.reindex(_grid, fill_value=0).cumsum()
    _cat_layer = _df.drop_duplicates("category").set_index("category")["layer"].to_dict()
    _order = _counts.iloc[-1].sort_values(ascending=False).index.tolist()
    _fig = go.Figure()
    for _cat in _order:
        _color = LAYER_COLORS.get(_cat_layer.get(_cat), C["ink_3"])
        _fig.add_trace(go.Scatter(
            x=_counts.index, y=_counts[_cat], mode="lines",
            line=dict(color=_color, width=2), showlegend=False,
            hovertemplate="<b>" + _cat + "</b><br>%{x|%b %Y}: %{y} projects<extra></extra>",
        ))
        _fig.add_annotation(
            x=_counts.index[-1], y=_counts[_cat].iloc[-1], text="  " + _cat,
            xanchor="left", yanchor="middle", showarrow=False,
            font=dict(family=F["mono"], size=9, color=_color),
        )
    _fig.update_layout(**LAYOUT, height=560)
    _fig.update_layout(
        title=dict(text="Cumulative open-source projects founded, by category",
                   font=dict(family=F["headline"], size=15, color=C["ink"]), x=0, xref="paper"),
        margin=dict(t=64, l=60, r=250, b=50),
    )
    _fig.update_xaxes(title="", showgrid=False, showline=True, linecolor=C["ink"],
                      tickfont=dict(size=11, color=C["ink_3"]))
    _fig.update_yaxes(title="Cumulative projects", showgrid=True, gridcolor=C["rule"],
                      showline=True, linecolor=C["ink"], tickfont=dict(size=11, color=C["ink_3"]))
    mo.ui.plotly(_fig, config={"displayModeBar": False})
    return


@app.cell(hide_code=True)
def methodology(C, F, mo):
    mo.Html(
        f'<div style="margin-top:52px; padding-top:20px; border-top:1px solid {C["rule"]};">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["ink_3"]}; '
        f'letter-spacing:0.08em; text-transform:uppercase; margin-bottom:8px;">Methodology</div>'
        f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; line-height:1.55;">'
        f'Contributor counts are distinct GitHub code committers (bots excluded) to the 199 scored open-stack '
        f'repositories over the trailing 12 months, from <span style="font-family:{F["mono"]};font-size:0.9em;">'
        f'currentai.scores.stack_contributors</span> (joined to the stack-map taxonomy bridge '
        f'<span style="font-family:{F["mono"]};font-size:0.9em;">currentai.catalog.stack_map</span>). '
        f'Growth uses monthly-active contributor counts from <span style="font-family:{F["mono"]};font-size:0.9em;">'
        f'currentai.metrics.daily</span> (excluding one viral 2025 outlier, OpenClaw, so growth is not a single-project artifact); geography is repo org-HQ from '
        f'<span style="font-family:{F["mono"]};font-size:0.9em;">currentai.scores.repos_summary</span>; '
        f'founding year is repo <span style="font-family:{F["mono"]};font-size:0.9em;">created_at</span>. '
        f'Closed-lab headcount is a rough public estimate of total employees (not just technical staff) and is '
        f'directional only. Underlying data: OSO / GitHub Archive.</p>'
        f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; margin-top:8px;">'
        f'<strong>Source:</strong> '
        f'<a href="https://www.oso.xyz" style="color:{C["accent"]}">Open Source Observer</a>, '
        f'<a href="https://map.currentai.org" style="color:{C["accent"]}">AI Stack Map</a></p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def load_inf(mo, pyoso_db_conn):
    df_inf = mo.sql(
        """
        SELECT product_name, repo, COUNT(DISTINCT developer_id) AS contributors
        FROM currentai.scores.stack_contributors
        WHERE category = 'inference_code'
        GROUP BY product_name, repo
        ORDER BY contributors DESC
        """,
        output=False, engine=pyoso_db_conn,
    )
    return (df_inf,)


@app.cell(hide_code=True)
def load_geo(mo, pyoso_db_conn):
    df_geo = mo.sql(
        """
        SELECT COALESCE(country, 'Unknown') AS country, COUNT(*) AS repos
        FROM currentai.scores.repos_summary
        WHERE LOWER(repo) IN (
          SELECT repo FROM currentai.catalog.stack_map WHERE openness_bucket IN ('open', 'open-ish')
        )
        GROUP BY COALESCE(country, 'Unknown')
        ORDER BY repos DESC
        """,
        output=False, engine=pyoso_db_conn,
    )
    return (df_geo,)


@app.cell(hide_code=True)
def load_tiers(mo, pyoso_db_conn):
    df_tiers = mo.sql(
        """
        WITH dev AS (
          SELECT developer_id, SUM(commits_12mo) AS commits
          FROM currentai.scores.stack_contributors
          WHERE openness_bucket IN ('open', 'open-ish')
          GROUP BY developer_id
        ),
        dev_oc AS (
          SELECT developer_id, SUM(commits_12mo) AS commits
          FROM currentai.scores.stack_contributors
          WHERE openness_bucket IN ('open', 'open-ish') AND repo <> 'openclaw/openclaw'
          GROUP BY developer_id
        )
        SELECT
          (SELECT COUNT(*) FROM dev) AS any_commit,
          (SELECT COUNT(*) FROM dev_oc) AS any_excl_oc,
          (SELECT COUNT(*) FROM dev WHERE commits >= 10) AS substantial,
          (SELECT COUNT(*) FROM dev WHERE commits >= 50) AS core
        """,
        output=False, engine=pyoso_db_conn,
    )
    return (df_tiers,)


@app.cell(hide_code=True)
def load_growth(mo, pyoso_db_conn):
    df_growth = mo.sql(
        """
        WITH m AS (
          SELECT d.repo, DATE_TRUNC('month', d.day) AS month, MAX(CAST(d.value AS INTEGER)) AS active
          FROM currentai.metrics.daily d
          WHERE d.metric = 'contributors'
            AND d.repo IN (SELECT repo FROM currentai.catalog.stack_map WHERE openness_bucket IN ('open', 'open-ish'))
            AND d.repo <> 'openclaw/openclaw'
          GROUP BY d.repo, DATE_TRUNC('month', d.day)
        )
        SELECT s.layer, m.month, SUM(m.active) AS active_contributors
        FROM m JOIN currentai.catalog.stack_map s ON m.repo = s.repo
        GROUP BY s.layer, m.month
        ORDER BY m.month, s.layer
        """,
        output=False, engine=pyoso_db_conn,
    )
    return (df_growth,)


@app.cell(hide_code=True)
def load_founding(mo, pyoso_db_conn):
    df_founding = mo.sql(
        """
        SELECT s.category, s.layer, r.created_at
        FROM currentai.entities.repos r
        JOIN currentai.catalog.stack_map s ON LOWER(r.repo) = s.repo
        WHERE s.openness_bucket IN ('open', 'open-ish') AND r.created_at IS NOT NULL
        """,
        output=False, engine=pyoso_db_conn,
    )
    return (df_founding,)


if __name__ == "__main__":
    app.run()
