import marimo

__generated_with = "unknown"
app = marimo.App(width="full")


@app.cell(hide_code=True)
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


@app.cell(hide_code=True)
def imports():
    import pandas as pd
    return (pd,)


@app.cell(hide_code=True)
def style():
    F = {
        "headline": "'Noto Serif', Georgia, serif",
        "body": "'Plus Jakarta Sans', -apple-system, system-ui, sans-serif",
        "mono": "'DM Mono', ui-monospace, SFMono-Regular, monospace",
    }
    C = {
        "ink": "#0b252f",
        "ink_2": "#272726",
        "ink_3": "#8fa1a4",
        "paper": "#f7f6f6",
        "paper_2": "#f2f1f1",
        "rule": "#edecec",
        "white": "#ffffff",
        "border": "#a5bbbe",
        "salmon": "#e86f57",
        "slate": "#3f5d68",
        "slate_lt": "#a5bbbe",
    }
    return C, F


@app.cell(hide_code=True)
def fonts(mo):
    mo.Html(
        '<style>'
        '@import url("https://fonts.googleapis.com/css2?family=DM+Mono:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&family=Noto+Serif:ital,wght@0,400;0,600;1,400&family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap");'
        '</style>'
    )
    return


@app.cell(hide_code=True)
def header(C, F, mo):
    mo.Html(
        f'<div style="padding:40px 0 28px; border-bottom:2px solid {C["ink"]}; margin-bottom:8px;">'
        f'<h1 style="font-family:{F["headline"]}; font-size:2.3rem; font-weight:600; '
        f'color:{C["ink"]}; margin:0 0 14px; line-height:1.05; letter-spacing:-0.025em;">'
        f'The long tail of open source AI</h1>'
        f'<p style="font-family:{F["body"]}; font-size:1.05rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.55;">'
        f'The open source AI universe beyond the scored gap map: every repository, model, and '
        f'package in the discovery set that has not yet been graded. Search and filter the full '
        f'long tail below.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def kpis(df_models, df_pkgs, df_repos, mo):
    _n = len(df_repos) + len(df_models) + len(df_pkgs)
    mo.hstack([
        mo.stat(label="Uncategorized artifacts", value=f"{_n:,}", bordered=True, caption="not yet in the gap map"),
        mo.stat(label="Repositories", value=f"{len(df_repos):,}", bordered=True, caption="all ≥500 GitHub stars"),
        mo.stat(label="Models", value=f"{len(df_models):,}", bordered=True, caption="Hugging Face Hub"),
        mo.stat(label="Packages", value=f"{len(df_pkgs):,}", bordered=True, caption="PyPI / npm / others"),
    ], widths="equal", gap=1)
    return


@app.cell(hide_code=True)
def table(C, F, df_models, df_pkgs, df_repos, mo):
    import json as _json
    import html as _html
    import math as _math

    def _s(x):
        return "" if x is None or (isinstance(x, float) and _math.isnan(x)) else str(x)

    def _n(x):
        try:
            return 0 if x is None or (isinstance(x, float) and _math.isnan(x)) else int(x)
        except (TypeError, ValueError):
            return 0

    _cats = []
    _cidx = {}

    def _ci(x):
        key = _s(x) or "(none)"
        if key not in _cidx:
            _cidx[key] = len(_cats)
            _cats.append(key)
        idx = _cidx[key]
        return idx

    # Unified positional rows: [kind, name, category_index, usage, meta, description]
    # kind 0=repo, 1=model, 2=package.
    _rows = []
    for _, _r in df_repos.iterrows():
        _rows.append([0, _s(_r["name"]), _ci(_r["category"]), _n(_r["stars"]),
                      _s(_r["meta"]), _s(_r["descr"])[:110]])
    for _, _r in df_models.iterrows():
        _rows.append([1, _s(_r["name"]), _ci(_r["category"]), _n(_r["downloads"]),
                      _s(_r["meta"]), ""])
    for _, _r in df_pkgs.iterrows():
        _rows.append([2, _s(_r["name"]), _ci(_r["category"]), 0, "", ""])

    _cfg = {
        "cats": _cats,
        "rows": _rows,
        "colors": {"ink": C["ink"], "ink3": C["ink_3"], "rule": C["rule"],
                   "paper2": C["paper_2"], "slate": C["slate"], "salmon": C["salmon"],
                   "pale": C["slate_lt"], "border": C["border"]},
        "fonts": {"mono": F["mono"], "body": F["body"]},
    }
    _cfg_js = _json.dumps(_cfg, separators=(",", ":")).replace("</", "<\\/")

    _css = (
        '<style>'
        "@import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Plus+Jakarta+Sans:wght@400;500;600&display=swap');"
        '*{margin:0;box-sizing:border-box}'
        'html,body{height:100%;background:#fff;font-family:"Plus Jakarta Sans",sans-serif;color:#0b252f}'
        '#bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;padding:4px 2px 12px}'
        '#bar input,#bar select{font-family:"DM Mono",monospace;font-size:12px;color:#0b252f;'
        'background:#fff;border:1px solid #a5bbbe;border-radius:0;padding:6px 10px;outline:none}'
        '#q{flex:1;min-width:200px}'
        '#count{font-family:"DM Mono",monospace;font-size:11px;color:#8fa1a4;margin-left:auto}'
        '#head,.row{display:flex;align-items:center;gap:10px;padding:0 8px}'
        '#head{height:30px;border-bottom:1px solid #a5bbbe;font-family:"DM Mono",monospace;'
        'font-size:9px;text-transform:uppercase;letter-spacing:0.08em;color:#8fa1a4}'
        '#scroll{height:560px;overflow-y:auto;border-bottom:1px solid #edecec;position:relative}'
        '#sizer{position:relative;width:100%}'
        '#vp{position:absolute;top:0;left:0;right:0}'
        '.row{height:38px;border-bottom:1px solid #edecec;font-size:13px}'
        '.row:hover{background:#f2f1f1}'
        '.c-type{width:62px;flex:none}.c-name{flex:1.4;min-width:0}.c-cat{width:150px;flex:none;color:#272726}'
        '.c-use{width:104px;flex:none;text-align:right;font-family:"DM Mono",monospace;font-size:12px}'
        '.c-meta{width:92px;flex:none;color:#8fa1a4;font-family:"DM Mono",monospace;font-size:11px}'
        '.c-desc{flex:1.6;min-width:0;color:#8fa1a4;font-size:12px}'
        '.ell{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}'
        '.badge{font-family:"DM Mono",monospace;font-size:9px;text-transform:uppercase;letter-spacing:0.04em;'
        'padding:2px 6px;color:#fff;display:inline-block}'
        'a{color:#0b252f;text-decoration:none}a:hover{text-decoration:underline}'
        '</style>'
    )
    _js = """
    const CFG = window.__LT__;
    const TC = ['Repo','Model','Pkg'];
    const TCOL = [CFG.colors.slate, CFG.colors.salmon, CFG.colors.pale];
    const fmt = (x) => x>=1e6 ? (x/1e6).toFixed(1)+'M' : x>=1e3 ? (x/1e3).toFixed(0)+'k' : (''+x);
    function url(row){
        const name=row[1], src=CFG.cats[row[2]];
        if(row[0]===0) return 'https://github.com/'+name;
        if(row[0]===1) return 'https://huggingface.co/'+name;
        const m={'PYPI':'https://pypi.org/project/','NPM':'https://www.npmjs.com/package/','NUGET':'https://www.nuget.org/packages/','CRATES':'https://crates.io/crates/','GO':'https://pkg.go.dev/'};
        return (m[src]||'#')==='#' ? '#' : m[src]+name;
    }
    function useCell(row){
        if(row[0]===0) return fmt(row[3])+' ★';
        if(row[0]===1) return fmt(row[3])+' dl';
        return CFG.cats[row[2]];
    }
    const ROWH=38, BUF=10;
    let filtered=[];
    const q=document.getElementById('q'), tf=document.getElementById('tf'), cf=document.getElementById('cf');
    const scroll=document.getElementById('scroll'), sizer=document.getElementById('sizer'), vp=document.getElementById('vp'), count=document.getElementById('count');

    function fillCats(){
        // categories present for the selected type
        const t=tf.value;
        const seen=new Set();
        for(const r of CFG.rows){ if(t==='' || (''+r[0])===t) seen.add(r[2]); }
        const opts=[...seen].map(i=>[CFG.cats[i],i]).sort((a,b)=>a[0].localeCompare(b[0]));
        cf.innerHTML='<option value="">All categories</option>'+opts.map(o=>'<option value="'+o[1]+'">'+o[0]+'</option>').join('');
    }
    function apply(){
        const term=q.value.trim().toLowerCase();
        const t=tf.value, cat=cf.value;
        filtered=[];
        for(const r of CFG.rows){
            if(t!=='' && (''+r[0])!==t) continue;
            if(cat!=='' && (''+r[2])!==cat) continue;
            if(term && r[1].toLowerCase().indexOf(term)<0 && (r[5]||'').toLowerCase().indexOf(term)<0) continue;
            filtered.push(r);
        }
        filtered.sort((a,b)=>(a[0]-b[0]) || (b[3]-a[3]) || a[1].localeCompare(b[1]));
        sizer.style.height=(filtered.length*ROWH)+'px';
        count.textContent=filtered.length.toLocaleString()+' of '+CFG.rows.length.toLocaleString();
        scroll.scrollTop=0; render();
    }
    function render(){
        const st=scroll.scrollTop;
        const start=Math.max(0, Math.floor(st/ROWH)-BUF);
        const end=Math.min(filtered.length, Math.ceil((st+scroll.clientHeight)/ROWH)+BUF);
        let h='';
        for(let i=start;i<end;i++){
            const r=filtered[i];
            h+='<div class="row">'
              +'<div class="c-type"><span class="badge" style="background:'+TCOL[r[0]]+'">'+TC[r[0]]+'</span></div>'
              +'<div class="c-name ell"><a href="'+url(r)+'" target="_blank" rel="noopener">'+r[1]+'</a></div>'
              +'<div class="c-cat ell">'+CFG.cats[r[2]]+'</div>'
              +'<div class="c-use">'+useCell(r)+'</div>'
              +'<div class="c-meta ell">'+(r[4]||'')+'</div>'
              +'<div class="c-desc ell">'+(r[5]||'')+'</div>'
              +'</div>';
        }
        vp.style.transform='translateY('+(start*ROWH)+'px)';
        vp.innerHTML=h;
    }
    q.addEventListener('input', apply);
    tf.addEventListener('change', ()=>{fillCats(); apply();});
    cf.addEventListener('change', apply);
    scroll.addEventListener('scroll', render);
    fillCats(); apply();
    """
    _body = (
        '<div id="bar">'
        '<input id="q" placeholder="Search name or description...">'
        '<select id="tf"><option value="">All types</option><option value="0" selected>Repositories</option>'
        '<option value="1">Models</option><option value="2">Packages</option></select>'
        '<select id="cf"></select>'
        '<span id="count"></span></div>'
        '<div id="head"><div class="c-type">Type</div><div class="c-name">Name</div>'
        '<div class="c-cat">Category</div><div class="c-use">Usage</div>'
        '<div class="c-meta">Lang / Lib</div><div class="c-desc">Description</div></div>'
        '<div id="scroll"><div id="sizer"><div id="vp"></div></div></div>'
    )
    _inner = (
        '<!DOCTYPE html><html><head><meta charset="utf-8">' + _css + '</head><body>'
        + _body + '<script>window.__LT__=' + _cfg_js + ';' + _js + '</script></body></html>'
    )
    _src = _html.escape(_inner, quote=True)
    mo.Html(
        '<div style="font-family:' + F["headline"] + ';font-size:15px;color:' + C["ink"]
        + ';margin:0 0 2px;">Browse the uncategorized long tail</div>'
        '<div style="font-family:' + F["mono"] + ';font-size:11px;color:' + C["ink_3"]
        + ';margin:0 0 8px;">Filter by type and category, sort is by usage (stars for repos, downloads for models).</div>'
        '<iframe srcdoc="' + _src + '" style="width:100%;height:710px;border:none;" scrolling="no"></iframe>'
    )
    return


@app.cell(hide_code=True)
def methodology(C, F, mo):
    mo.Html(
        f'<div style="margin-top:44px; padding-top:20px; border-top:1px solid {C["rule"]};">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["ink_3"]}; '
        f'letter-spacing:0.08em; text-transform:uppercase; margin-bottom:8px;">Methodology</div>'
        f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; line-height:1.55;">'
        f'The long tail is every artifact in the discovery universe that is not part of a scored gap-map '
        f'product. Repositories come from <span style="font-family:{F["mono"]};font-size:0.9em;">'
        f'currentai.scores.repos_summary</span> (the GoodAI List catalog, all at or above 500 GitHub stars), '
        f'models from <span style="font-family:{F["mono"]};font-size:0.9em;">currentai.entities.models</span> '
        f'(Hugging Face Hub), and packages from <span style="font-family:{F["mono"]};font-size:0.9em;">'
        f'currentai.entities.packages</span>. Artifacts whose repository is already in the gap map are '
        f'excluded via <span style="font-family:{F["mono"]};font-size:0.9em;">currentai.catalog.stack_map</span>. '
        f'Categories are the source taxonomies as published: GoodAI List categories for repositories, '
        f'Hugging Face pipeline tags for models, and the registry for packages. Usage is GitHub stars for '
        f'repositories and Hugging Face downloads for models.</p>'
        f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; margin-top:8px;">'
        f'<strong>Sources:</strong> '
        f'<a href="https://www.oso.xyz" style="color:{C["ink"]}">OSO</a>, '
        f'<a href="https://goodailist.com" style="color:{C["ink"]}">GoodAI List</a>, '
        f'<a href="https://huggingface.co" style="color:{C["ink"]}">Hugging Face Hub</a>, '
        f'<a href="https://pypi.org" style="color:{C["ink"]}">PyPI</a>, '
        f'<a href="https://www.npmjs.com" style="color:{C["ink"]}">npm</a></p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def load_repos(mo, pyoso_db_conn):
    df_repos = mo.sql(
        """
        SELECT repo AS name, category, CAST(stars AS DOUBLE) AS stars,
               language AS meta, description AS descr
        FROM currentai.scores.repos_summary
        WHERE LOWER(repo) NOT IN (SELECT repo FROM currentai.catalog.stack_map)
        """,
        output=False, engine=pyoso_db_conn,
    )
    return (df_repos,)


@app.cell(hide_code=True)
def load_models(mo, pyoso_db_conn):
    df_models = mo.sql(
        """
        SELECT model_id AS name, pipeline_tag AS category,
               CAST(downloads AS DOUBLE) AS downloads, library_name AS meta
        FROM currentai.entities.models
        WHERE repo IS NULL OR LOWER(repo) NOT IN (SELECT repo FROM currentai.catalog.stack_map)
        """,
        output=False, engine=pyoso_db_conn,
    )
    return (df_models,)


@app.cell(hide_code=True)
def load_packages(mo, pyoso_db_conn):
    df_pkgs = mo.sql(
        """
        SELECT package_name AS name, package_source AS category
        FROM currentai.entities.packages
        WHERE repo IS NULL OR LOWER(repo) NOT IN (SELECT repo FROM currentai.catalog.stack_map)
        """,
        output=False, engine=pyoso_db_conn,
    )
    return (df_pkgs,)


if __name__ == "__main__":
    app.run()
