import marimo

__generated_with = "unknown"
app = marimo.App()


@app.cell(hide_code=True)
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


@app.cell(hide_code=True)
def imports():
    import pandas as pd
    return


@app.cell(hide_code=True)
def style():
    F = {
        "headline": "'Noto Serif', Georgia, serif",
        "body": "'Plus Jakarta Sans', -apple-system, system-ui, sans-serif",
        "mono": "'DM Mono', ui-monospace, SFMono-Regular, monospace",
    }
    C = {
        "ink": "#0b252f",
        "ink_2": "#272726",
        "ink_3": "#8fa1a4",
        "paper": "#f7f6f6",
        "paper_2": "#f2f1f1",
        "rule": "#edecec",
        "white": "#ffffff",
        "border": "#a5bbbe",
        "salmon": "#e86f57",
        "slate": "#3f5d68",
        "slate_lt": "#a5bbbe",
    }
    return C, F


@app.cell(hide_code=True)
def fonts(mo):
    mo.Html(
        '<style>'
        '@import url("https://fonts.googleapis.com/css2?family=DM+Mono:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&family=Noto+Serif:ital,wght@0,400;0,600;1,400&family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap");'
        '</style>'
    )
    return


@app.cell(hide_code=True)
def header(C, F, mo):
    mo.Html(
        f'<div style="padding:40px 0 28px; border-bottom:2px solid {C["ink"]}; margin-bottom:8px;">'
        f'<h1 style="font-family:{F["headline"]}; font-size:2.3rem; font-weight:600; '
        f'color:{C["ink"]}; margin:0 0 14px; line-height:1.05; letter-spacing:-0.025em;">'
        f'The long tail of open source AI</h1>'
        f'<p style="font-family:{F["body"]}; font-size:1.05rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.55;">'
        f'The open source AI universe beyond the scored gap map: every repository, model, and '
        f'package in the discovery set that has not yet been graded. Search and filter the full '
        f'long tail below.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def kpis(df_models, df_pkgs, df_repos, mo):
    _n = len(df_repos) + len(df_models) + len(df_pkgs)
    mo.hstack([
        mo.stat(label="Uncategorized artifacts", value=f"{_n:,}", bordered=True, caption="not yet in the gap map"),
        mo.stat(label="Repositories", value=f"{len(df_repos):,}", bordered=True, caption="all ≥500 GitHub stars"),
        mo.stat(label="Models", value=f"{len(df_models):,}", bordered=True, caption="Hugging Face Hub"),
        mo.stat(label="Packages", value=f"{len(df_pkgs):,}", bordered=True, caption="PyPI / npm / others"),
    ], widths="equal", gap=1)
    return


@app.cell(hide_code=True)
def table(C, F, df_models, df_pkgs, df_repos, mo):
    import json as _json
    import html as _html
    import math as _math
    import gzip as _gzip
    import base64 as _base64

    def _s(x):
        return "" if x is None or (isinstance(x, float) and _math.isnan(x)) else str(x)

    def _n(x):
        try:
            return 0 if x is None or (isinstance(x, float) and _math.isnan(x)) else int(x)
        except (TypeError, ValueError):
            return 0

    _cats = []
    _cidx = {}

    def _ci(x):
        key = _s(x) or "(none)"
        if key not in _cidx:
            _cidx[key] = len(_cats)
            _cats.append(key)
        idx = _cidx[key]
        return idx

    # Unified positional rows: [kind, name, category_index, usage, meta, description]
    # kind 0=repo, 1=model, 2=package.
    _rows = []
    for _, _r in df_repos.iterrows():
        _rows.append([0, _s(_r["name"]), _ci(_r["category"]), _n(_r["stars"]),
                      _s(_r["meta"]), _s(_r["descr"])[:110]])
    for _, _r in df_models.iterrows():
        _rows.append([1, _s(_r["name"]), _ci(_r["category"]), _n(_r["downloads"]),
                      _s(_r["meta"]), ""])
    for _, _r in df_pkgs.iterrows():
        _rows.append([2, _s(_r["name"]), _ci(_r["category"]), 0, "", ""])

    _cfg = {
        "cats": _cats,
        "rows": _rows,
        "colors": {"ink": C["ink"], "ink3": C["ink_3"], "rule": C["rule"],
                   "paper2": C["paper_2"], "slate": C["slate"], "salmon": C["salmon"],
                   "pale": C["slate_lt"], "border": C["border"]},
        "fonts": {"mono": F["mono"], "body": F["body"]},
    }
    # ~60k rows as raw JSON lands close to marimo's 5MB output_max_bytes cap
    # (and an escaped iframe srcdoc attribute inflates every quote 6x on top of
    # that), so the payload ships gzipped + base64 instead of inline JSON.
    _cfg_json = _json.dumps(_cfg, separators=(",", ":"))
    _gz_b64 = _base64.b64encode(_gzip.compress(_cfg_json.encode("utf-8"), 9)).decode("ascii")

    _css = (
        '<style>'
        "@import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Plus+Jakarta+Sans:wght@400;500;600&display=swap');"
        '*{margin:0;box-sizing:border-box}'
        'html,body{height:100%;background:#fff;font-family:"Plus Jakarta Sans",sans-serif;color:#0b252f}'
        '#bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;padding:4px 2px 12px}'
        '#bar input,#bar select{font-family:"DM Mono",monospace;font-size:12px;color:#0b252f;'
        'background:#fff;border:1px solid #a5bbbe;border-radius:0;padding:6px 10px;outline:none}'
        '#q{flex:1;min-width:200px}'
        '#count{font-family:"DM Mono",monospace;font-size:11px;color:#8fa1a4;margin-left:auto}'
        '#head,.row{display:flex;align-items:center;gap:10px;padding:0 8px;'
        'font-family:"Plus Jakarta Sans",sans-serif;font-size:13px;color:#0b252f}'
        '#head{height:34px;border-bottom:1px solid #a5bbbe;font-weight:600;color:#8fa1a4}'
        '#scroll{height:560px;overflow-y:auto;border-bottom:1px solid #edecec;position:relative}'
        '#sizer{position:relative;width:100%}'
        '#vp{position:absolute;top:0;left:0;right:0}'
        '.row{height:38px;border-bottom:1px solid #edecec}'
        '.row:hover{background:#f2f1f1}'
        '.c-type{width:62px;flex:none}.c-name{flex:1.4;min-width:0}.c-cat{width:150px;flex:none}'
        '.c-use{width:104px;flex:none;text-align:right}'
        '.c-meta{width:92px;flex:none}'
        '.c-desc{flex:1.6;min-width:0}'
        '.row .c-cat{color:#272726}'
        '.row .c-use{font-family:"DM Mono",monospace}'
        '.row .c-meta{color:#8fa1a4}'
        '.row .c-desc{color:#8fa1a4}'
        '.ell{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}'
        '.badge{font-family:"DM Mono",monospace;font-size:9px;text-transform:uppercase;letter-spacing:0.04em;'
        'padding:2px 6px;color:#fff;display:inline-block}'
        'a{color:#0b252f;text-decoration:none}a:hover{text-decoration:underline}'
        '</style>'
    )
    _js = """
    let CFG;
    const TC = ['Repo','Model','Pkg'];
    const fmt = (x) => x>=1e6 ? (x/1e6).toFixed(1)+'M' : x>=1e3 ? (x/1e3).toFixed(0)+'k' : (''+x);
    function tcol(i){ return [CFG.colors.slate, CFG.colors.salmon, CFG.colors.pale][i]; }
    function url(row){
        const name=row[1], src=CFG.cats[row[2]];
        if(row[0]===0) return 'https://github.com/'+name;
        if(row[0]===1) return 'https://huggingface.co/'+name;
        const m={'PIP':'https://pypi.org/project/','NPM':'https://www.npmjs.com/package/','NUGET':'https://www.nuget.org/packages/','RUST':'https://crates.io/crates/','GO':'https://pkg.go.dev/','MAVEN':'https://search.maven.org/artifact/','GEM':'https://rubygems.org/gems/'};
        return (m[src]||'#')==='#' ? '#' : m[src]+name;
    }
    function useCell(row){
        if(row[0]===0) return fmt(row[3])+' ★';
        if(row[0]===1) return fmt(row[3])+' dl/30d';
        return CFG.cats[row[2]];
    }
    const ROWH=38, BUF=10;
    let filtered=[];
    const q=document.getElementById('q'), tf=document.getElementById('tf'), cf=document.getElementById('cf');
    const scroll=document.getElementById('scroll'), sizer=document.getElementById('sizer'), vp=document.getElementById('vp'), count=document.getElementById('count');

    function fillCats(){
        // categories present for the selected type
        const t=tf.value;
        const seen=new Set();
        for(const r of CFG.rows){ if(t==='' || (''+r[0])===t) seen.add(r[2]); }
        const opts=[...seen].map(i=>[CFG.cats[i],i]).sort((a,b)=>a[0].localeCompare(b[0]));
        cf.innerHTML='<option value="">All categories</option>'+opts.map(o=>'<option value="'+o[1]+'">'+o[0]+'</option>').join('');
    }
    function apply(){
        const term=q.value.trim().toLowerCase();
        const t=tf.value, cat=cf.value;
        filtered=[];
        for(const r of CFG.rows){
            if(t!=='' && (''+r[0])!==t) continue;
            if(cat!=='' && (''+r[2])!==cat) continue;
            if(term && r[1].toLowerCase().indexOf(term)<0 && (r[5]||'').toLowerCase().indexOf(term)<0) continue;
            filtered.push(r);
        }
        filtered.sort((a,b)=>(a[0]-b[0]) || (b[3]-a[3]) || a[1].localeCompare(b[1]));
        sizer.style.height=(filtered.length*ROWH)+'px';
        count.textContent=filtered.length.toLocaleString()+' of '+CFG.rows.length.toLocaleString();
        scroll.scrollTop=0; render();
    }
    function render(){
        const st=scroll.scrollTop;
        const start=Math.max(0, Math.floor(st/ROWH)-BUF);
        const end=Math.min(filtered.length, Math.ceil((st+scroll.clientHeight)/ROWH)+BUF);
        let h='';
        for(let i=start;i<end;i++){
            const r=filtered[i];
            h+='<div class="row">'
              +'<div class="c-type"><span class="badge" style="background:'+tcol(r[0])+'">'+TC[r[0]]+'</span></div>'
              +'<div class="c-name ell"><a href="'+url(r)+'" target="_blank" rel="noopener">'+r[1]+'</a></div>'
              +'<div class="c-cat ell">'+CFG.cats[r[2]]+'</div>'
              +'<div class="c-use">'+useCell(r)+'</div>'
              +'<div class="c-meta ell">'+(r[4]||'')+'</div>'
              +'<div class="c-desc ell">'+(r[5]||'')+'</div>'
              +'</div>';
        }
        vp.style.transform='translateY('+(start*ROWH)+'px)';
        vp.innerHTML=h;
    }
    q.addEventListener('input', apply);
    tf.addEventListener('change', ()=>{fillCats(); apply();});
    cf.addEventListener('change', apply);
    scroll.addEventListener('scroll', render);

    async function boot(){
        try {
            const b64 = document.getElementById('ltdata').textContent;
            const bin = atob(b64);
            const bytes = new Uint8Array(bin.length);
            for (let i=0;i<bin.length;i++) bytes[i] = bin.charCodeAt(i);
            const ds = new DecompressionStream('gzip');
            const stream = new Blob([bytes]).stream().pipeThrough(ds);
            CFG = JSON.parse(await new Response(stream).text());
        } catch (e) {
            scroll.innerHTML = '<div style="padding:24px;color:#a33328;font-size:12px;">Could not unpack data: '+String(e)+'</div>';
            return;
        }
        fillCats(); apply();
    }
    boot();
    """
    _body = (
        '<div id="bar">'
        '<input id="q" placeholder="Search name or description...">'
        '<select id="tf"><option value="">All types</option><option value="0" selected>Repositories</option>'
        '<option value="1">Models</option><option value="2">Packages</option></select>'
        '<select id="cf"></select>'
        '<span id="count"></span></div>'
        '<div id="head"><div class="c-type">Type</div><div class="c-name">Name</div>'
        '<div class="c-cat">Category</div><div class="c-use">Usage</div>'
        '<div class="c-meta">Lang / Lib</div><div class="c-desc">Description</div></div>'
        '<div id="scroll"><div id="sizer"><div id="vp"></div></div></div>'
        '<script id="ltdata" type="application/octet-stream">' + _gz_b64 + '</script>'
    )
    _inner = (
        '<!DOCTYPE html><html><head><meta charset="utf-8">' + _css + '</head><body>'
        + _body + '<script>' + _js + '</script></body></html>'
    )
    _src = _html.escape(_inner, quote=True)

    _MAX_OUTPUT_BYTES = 5_000_000
    _out_bytes = len(_src.encode("utf-8"))
    if _out_bytes > _MAX_OUTPUT_BYTES:
        raise AssertionError(
            f"long-tail table output is {_out_bytes:,} bytes, over marimo's "
            f"output_max_bytes cap of {_MAX_OUTPUT_BYTES:,}. Apply a stars/"
            f"downloads floor to cut row count before publishing."
        )

    mo.Html(
        '<div style="font-family:' + F["headline"] + ';font-size:15px;color:' + C["ink"]
        + ';margin:0 0 2px;">Browse the uncategorized long tail</div>'
        '<div style="font-family:' + F["mono"] + ';font-size:11px;color:' + C["ink_3"]
        + ';margin:0 0 8px;">Filter by type and category, sort is by usage (stars for repos, 30-day downloads for models).</div>'
        '<iframe srcdoc="' + _src + '" style="width:100%;height:710px;border:none;" scrolling="no"></iframe>'
    )
    return


@app.cell(hide_code=True)
def methodology(C, F, mo):
    mo.Html(
        f'<div style="margin-top:44px; padding-top:20px; border-top:1px solid {C["rule"]};">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["ink_3"]}; '
        f'letter-spacing:0.08em; text-transform:uppercase; margin-bottom:8px;">Methodology</div>'
        f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; line-height:1.55;">'
        f'The long tail is every artifact in the discovery universe that is not yet part of a scored gap-map '
        f'product. Repositories come from <span style="font-family:{F["mono"]};font-size:0.9em;">'
        f'currentai.signal_goodailist.repo_catalog</span> (the GoodAI List catalog, all at or above 500 GitHub '
        f'stars), models from <span style="font-family:{F["mono"]};font-size:0.9em;">'
        f'currentai.signal_hfhub.model_universe</span> (Hugging Face Hub, at or above 1,000 downloads in the '
        f'trailing 30 days), and packages from <span style="font-family:{F["mono"]};font-size:0.9em;">'
        f'oso.package_owners_v0</span> joined to the repo catalog — every package published by a catalog '
        f'repository, not a dependency of one. An artifact is excluded once <span style="font-family:'
        f'{F["mono"]};font-size:0.9em;">currentai.registry.product_artifacts</span> records it as scored: a '
        f'repository by its GitHub identifier, a model by its Hugging Face ID, and a package by its registry '
        f'name (PyPI, npm, or crates.io). Categories are the source taxonomies as published: GoodAI List '
        f'categories for repositories, Hugging Face pipeline tags for models, and the package registry for '
        f'packages. Usage is GitHub stars for repositories and Hugging Face downloads in the trailing 30 days '
        f'for models.</p>'
        f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; margin-top:8px;">'
        f'<strong>Sources:</strong> '
        f'<a href="https://www.oso.xyz" style="color:{C["ink"]}">OSO</a>, '
        f'<a href="https://goodailist.com" style="color:{C["ink"]}">GoodAI List</a>, '
        f'<a href="https://huggingface.co" style="color:{C["ink"]}">Hugging Face Hub</a>, '
        f'<a href="https://pypi.org" style="color:{C["ink"]}">PyPI</a>, '
        f'<a href="https://www.npmjs.com" style="color:{C["ink"]}">npm</a>, '
        f'<a href="https://crates.io" style="color:{C["ink"]}">crates.io</a></p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def load_repos(mo, pyoso_db_conn):
    df_repos = mo.sql(
        f"""
        SELECT
            r.repo AS name, r.category AS category,
            CAST(r.stars AS DOUBLE) AS stars,
            r.language AS meta, r.description AS descr
        FROM currentai.signal_goodailist.repo_catalog r
        WHERE NOT EXISTS (
            SELECT 1 FROM currentai.registry.product_artifacts pa
            WHERE pa.artifact_kind = 'github'
              AND LOWER(pa.artifact_id) = LOWER(r.repo)
        )
        """,
        output=False,
        engine=pyoso_db_conn
    )
    return (df_repos,)


@app.cell(hide_code=True)
def load_models(mo, pyoso_db_conn):
    df_models = mo.sql(
        f"""
        SELECT
            m.hf_id AS name, m.pipeline_tag AS category,
            CAST(m.downloads_30d AS DOUBLE) AS downloads,
            m.library_name AS meta
        FROM currentai.signal_hfhub.model_universe m
        WHERE NOT EXISTS (
            SELECT 1 FROM currentai.registry.product_artifacts pa
            WHERE pa.artifact_kind = 'huggingface_model'
              AND LOWER(pa.artifact_id) = LOWER(m.hf_id)
        )
        """,
        output=False,
        engine=pyoso_db_conn
    )
    return (df_models,)


@app.cell(hide_code=True)
def load_packages(mo, pyoso_db_conn):
    df_pkgs = mo.sql(
        f"""
        WITH pkgs AS (
            SELECT DISTINCT
                p.package_artifact_source AS category,
                p.package_artifact_name AS name
            FROM oso.package_owners_v0 p
            JOIN currentai.signal_goodailist.repo_catalog r
              ON LOWER(p.package_owner_artifact_namespace || '/' || p.package_owner_artifact_name) = LOWER(r.repo)
        )
        SELECT pk.name AS name, pk.category AS category
        FROM pkgs pk
        WHERE NOT EXISTS (
            SELECT 1 FROM currentai.registry.product_artifacts pa
            WHERE LOWER(pa.artifact_id) = LOWER(pk.name)
              AND (
                  (pk.category = 'PIP' AND pa.artifact_kind = 'pypi') OR
                  (pk.category = 'NPM' AND pa.artifact_kind = 'npm') OR
                  (pk.category = 'RUST' AND pa.artifact_kind = 'crates')
              )
        )
        """,
        output=False,
        engine=pyoso_db_conn
    )
    return (df_pkgs,)


if __name__ == "__main__":
    app.run()
