import marimo

__generated_with = "unknown"
app = marimo.App(width="full")


@app.cell(hide_code=True)
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


@app.cell(hide_code=True)
def imports():
    import plotly.graph_objects as go
    return (go,)


@app.cell(hide_code=True)
def style():
    F = {
        "headline": "'Noto Serif', Georgia, serif",
        "body": "'Plus Jakarta Sans', -apple-system, system-ui, sans-serif",
        "mono": "'DM Mono', ui-monospace, SFMono-Regular, monospace",
    }
    C = {
        # Shared neutrals + structure (match ai-stack-map / products-view).
        "ink": "#0b252f",
        "ink_2": "#272726",
        "ink_3": "#8fa1a4",
        "paper": "#f7f6f6",
        "paper_2": "#f2f1f1",
        "rule": "#edecec",
        "white": "#ffffff",
        "border": "#a5bbbe",
        # Brand salmon ramp: deep = emphasis/highlight, fading to pale coral.
        "healthy": "#e86f57",
        "warm": "#f4886f",
        "signal": "#f8ad99",
        # Navy accent + cool slate pair for magnitude/secondary series.
        "accent": "#0b252f",
        "slate": "#3f5d68",
        "slate_mid": "#5f7e88",
        "slate_lt": "#a5bbbe",
    }
    LAYOUT = dict(
        plot_bgcolor="white",
        paper_bgcolor="white",
        font=dict(family=F["body"], size=12, color=C["ink"]),
        margin=dict(t=20, l=60, r=20, b=50),
        legend=dict(
            bgcolor="rgba(0,0,0,0)",
            font=dict(size=11),
            orientation="h",
            yanchor="bottom", y=1.02,
            xanchor="left", x=0,
        ),
        hovermode="closest",
    )
    CHART_LAYOUT = LAYOUT
    CAT_COLORS = {
        # Brand-harmonised categorical palette: cool navy->slate ramp for the
        # build/infra layers, salmon for the consumer-facing model/app layers,
        # muted slates for the long-tail buckets. No rainbow, keeping the
        # restrained two-family brand system of the AI Stack Map.
        "Infrastructure": "#0b252f",     # navy
        "AI Engineering": "#3f5d68",     # dark slate
        "Model Development": "#5f7e88",  # mid slate
        "Models": "#e86f57",             # deep salmon (headline layer)
        "Applications": "#f4886f",       # salmon
        "Tutorials": "#8aa6ac",          # light slate
        "Lists": "#a5bbbe",              # pale slate
        "Misc": "#c9d4d6",               # faint slate
    }
    return C, CAT_COLORS, CHART_LAYOUT, F, LAYOUT


@app.cell(hide_code=True)
def fonts(mo):
    mo.Html(
        '<style>'
        '@import url("https://fonts.googleapis.com/css2?family=DM+Mono:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&family=Noto+Serif:ital,wght@0,400;0,600;1,400&family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap");'
        '</style>'
    )
    return


@app.cell(hide_code=True)
def header(C, F, mo):
    mo.Html(
        f'<div style="padding:40px 0 28px; border-bottom:2px solid {C["accent"]}; margin-bottom:36px;">'
        f'<h1 style="font-family:{F["headline"]}; font-size:2.2rem; font-weight:600; '
        f'color:{C["ink"]}; margin:0 0 14px; line-height:1.05; letter-spacing:-0.025em;">'
        f'Open-Source AI Ecosystem Trends</h1>'
        f'<p style="font-family:{F["body"]}; font-size:1rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.5;">'
        f'Growth signals across the open-source AI landscape. '
        f'Data sourced from OSO and Good AI List.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def load_oss_ai_repos(mo, pyoso_db_conn):
    df_gl = mo.sql(
        f"""
        SELECT
          repo,
          SPLIT_PART(repo, '/', 1) AS owner,
          category,
          subcategory AS primary_subcat,
          CAST(stars AS DOUBLE) AS stars,
          CAST(contributors AS DOUBLE) AS contributors,
          CAST(star_7d AS DOUBLE) AS star_7d
        FROM currentai.scores.repos_summary
        """,
        output=False,
        engine=pyoso_db_conn
    )
    return (df_gl,)


@app.cell(hide_code=True)
def compute_subcat_health(df_gl):
    df_subcat = df_gl.groupby(['category', 'primary_subcat']).agg(
        repos=('repo', 'count'),
        total_stars=('stars', 'sum'),
        median_stars=('stars', 'median'),
        median_contributors=('contributors', 'median'),
        weekly_stars=('star_7d', 'sum'),
    ).reset_index()
    return (df_subcat,)


@app.cell(hide_code=True)
def load_repo_activity(mo, pyoso_db_conn):
    df_stars_forks = mo.sql(
        f"""
        SELECT
          repo,
          stars_90d AS stars_3m,
          forks_90d AS forks_3m
        FROM currentai.scores.repos_summary
        ORDER BY stars_3m DESC
        """,
        output=False,
        engine=pyoso_db_conn
    )
    return (df_stars_forks,)


@app.cell(hide_code=True)
def load_contributors(mo, pyoso_db_conn):
    df_contributors = mo.sql(
        f"""
        SELECT
          repo,
          total_contributors,
          full_time,
          part_time
        FROM currentai.scores.repos_summary
        WHERE total_contributors > 0
        ORDER BY total_contributors DESC
        """,
        output=False,
        engine=pyoso_db_conn
    )
    return (df_contributors,)


@app.cell(hide_code=True)
def load_monthly(mo, pyoso_db_conn):
    df_monthly = mo.sql(
        f"""
        SELECT
          r.category,
          DATE_TRUNC('month', m.day) AS month,
          MAX(CASE WHEN m.metric = 'contributors' THEN CAST(m.value AS INTEGER) ELSE 0 END) AS active_devs,
          MAX(CASE WHEN m.metric = 'full_time' THEN CAST(m.value AS INTEGER) ELSE 0 END) AS full_time,
          MAX(CASE WHEN m.metric = 'part_time' THEN CAST(m.value AS INTEGER) ELSE 0 END) AS part_time
        FROM currentai.metrics.daily m
        JOIN currentai.scores.repos_summary r ON m.repo = r.repo
        WHERE m.metric IN ('contributors', 'full_time', 'part_time')
        GROUP BY r.category, DATE_TRUNC('month', m.day)
        ORDER BY month, r.category
        """,
        output=False,
        engine=pyoso_db_conn
    )
    return (df_monthly,)


@app.cell(hide_code=True)
def source_stats(df_contributors, df_gl, df_stars_forks, mo):
    mo.hstack([
        mo.stat(label="Repos", value=f"{len(df_gl):,}", bordered=True, caption="OSS AI repos"),
        mo.stat(label="Unique orgs", value=f"{df_gl['owner'].nunique():,}", bordered=True, caption="GitHub organizations"),
        mo.stat(label="Categories", value=str(df_gl['category'].nunique()), bordered=True, caption="top-level taxonomy"),
        mo.stat(label="Stars (3mo)", value=f"{df_stars_forks['stars_3m'].sum()/1e6:.1f}M", bordered=True, caption="new stars, last 90 days"),
        mo.stat(label="Forks (3mo)", value=f"{df_stars_forks['forks_3m'].sum()/1e3:.0f}K", bordered=True, caption="new forks, last 90 days"),
        mo.stat(label="Contributors", value=f"{df_contributors['total_contributors'].sum()/1e3:.0f}K", bordered=True, caption="active devs, last 90 days"),
    ], widths="equal", gap=1)
    return


@app.cell(hide_code=True)
def section_monthly(C, F, mo):
    mo.Html(
        f'<div style="margin:44px 0 20px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">'
        f'Developer Activity</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.6rem; font-weight:600;'
        f'color:{C["ink"]}; margin:0 0 8px;">Monthly active developers by category</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.9rem; color:{C["ink_3"]}; '
        f'margin:0; line-height:1.5;">'
        f'Select a category to see full-time vs part-time developer breakdown over the last 90 days.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def monthly_active_chart(CAT_COLORS, C, F, df_monthly, go, mo):
    import json as _json
    import html as _html
    import pandas as _pd

    df_monthly['month'] = _pd.to_datetime(df_monthly['month'])
    _categories = sorted(df_monthly['category'].dropna().unique().tolist())

    _states = {}
    for _cat in _categories:
        _df = df_monthly[df_monthly['category'] == _cat].sort_values('month')
        if _df.empty:
            continue

        _latest = _df['month'].max()
        _latest_r = _df[_df['month'] == _latest].iloc[0]
        _active = int(_latest_r['active_devs'])
        _ft = int(_latest_r['full_time'])
        _pt = int(_latest_r['part_time'])

        def _stat(value, label, caption=''):
            return (
                f'<div style="border:1px solid {C["rule"]};border-radius:0;padding:12px 16px;flex:1;min-width:100px;">'
                f'<div style="font-family:{F["mono"]};font-size:1.5em;font-weight:600;color:{C["ink"]};line-height:1.2;">{value}</div>'
                f'<div style="font-family:{F["body"]};font-size:0.6875em;font-weight:500;color:{C["ink_3"]};text-transform:uppercase;letter-spacing:0.03em;margin-bottom:4px;">{label}</div>'
                + (f'<div style="font-family:{F["body"]};font-size:0.75em;color:{C["ink_3"]};margin-top:4px;">{caption}</div>' if caption else '')
                + '</div>'
            )

        _stats_html = (
            f'<div style="display:flex;gap:12px;margin:12px 0;">'
            + _stat(f'{_active:,}', 'Active Developers', f'Latest month ({str(_latest)[:7]})')
            + _stat(f'{_ft:,}', 'Full-Time', '≥ 10 active days/month')
            + _stat(f'{_pt:,}', 'Part-Time', '1–9 active days/month')
            + '</div>'
        )

        _color = CAT_COLORS.get(_cat, C['accent'])
        _fig = go.Figure()
        _month_labels = [str(m)[:7] for m in _df['month']]
        _fig.add_trace(go.Bar(
            x=_month_labels, y=_df['full_time'],
            name='Full-Time', marker_color=_color,
            hovertemplate='<b>Full-Time</b><br>%{x}: %{y:,}<extra></extra>',
        ))
        _fig.add_trace(go.Bar(
            x=_month_labels, y=_df['part_time'],
            name='Part-Time', marker_color=_color, marker_opacity=0.5,
            hovertemplate='<b>Part-Time</b><br>%{x}: %{y:,}<extra></extra>',
        ))
        _fig.update_layout(
            barmode='stack',
            height=420,
            plot_bgcolor='white', paper_bgcolor='white',
            font=dict(family=F['body'], size=12, color=C['ink']),
            margin=dict(t=40, l=60, r=40, b=50),
            hovermode='x unified',
            showlegend=True,
            legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1, bgcolor='rgba(255,255,255,0.8)'),
            xaxis=dict(type='category', showgrid=False, showline=True, linecolor=C['ink'], linewidth=1,
                       tickfont=dict(size=11, color=C['ink_3'])),
            yaxis=dict(showgrid=True, gridcolor=C['rule'], showline=True, linecolor=C['ink'],
                       linewidth=1, tickfont=dict(size=11, color=C['ink_3']), title='Active developers', tickformat=',d'),
        )
        _states[_cat] = {'stats': _stats_html, 'chart': _json.loads(_fig.to_json())}

    _opts = [c for c in _categories if c in _states]
    _djs_safe = _json.dumps(_states).replace('</', '<\\/')
    _opts_js = _json.dumps(_opts)
    _sel_html = (
        f'<div style="margin-bottom:8px">'
        f'<span style="font-family:{F["mono"]};font-size:0.6875em;color:{C["ink_3"]};display:block;margin-bottom:2px;">Category</span>'
        f'<select id="sel" style="padding:4px 8px;border:1px solid {C["border"]};border-radius:0;'
        f'font-family:{F["body"]};font-size:0.8125em;color:{C["ink"]};background:white;cursor:pointer;outline:none;">'
        + ''.join(f'<option value="{i}">{o}</option>' for i, o in enumerate(_opts))
        + '</select></div>'
    )

    _inner = (
        '<!DOCTYPE html><html><head><meta charset="utf-8">'
        '<script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>'
        f'<style>*{{box-sizing:border-box;margin:0;padding:0;'
        f'font-family:{F["body"]}!important}}'
        f'body{{font-size:14px;color:{C["ink"]};padding:4px}}'
        f'</style></head><body>'
        f'{_sel_html}'
        '<div id="stats" style="margin-bottom:4px"></div>'
        '<div id="chart"></div>'
        f'<script>var D={_djs_safe};var O={_opts_js};'
        'var sel=document.getElementById("sel");'
        'function show(i){'
        'document.getElementById("stats").innerHTML=D[O[i]].stats||"";'
        'Plotly.react("chart",D[O[i]].chart.data,D[O[i]].chart.layout,{responsive:true,displayModeBar:false});}'
        'sel.addEventListener("change",function(){show(parseInt(this.value))});'
        'show(0);'
        '</script></body></html>'
    )
    _src = _html.escape(_inner, quote=True)

    mo.Html(f'<iframe srcdoc="{_src}" style="width:100%;height:560px;border:none;" scrolling="no"></iframe>')
    return


@app.cell(hide_code=True)
def section_momentum(C, F, mo):
    mo.Html(
        f'<div style="margin:44px 0 20px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">'
        f'Momentum</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.6rem; font-weight:600;'
        f'color:{C["ink"]}; margin:0 0 8px;">7-day star velocity</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.9rem; color:{C["ink_3"]}; '
        f'margin:0; line-height:1.5;">'
        f'Weekly star growth reveals where developer attention is flowing right now. '
        f'Top 25 subcategories with ≥10 repos.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def momentum_bar(CAT_COLORS, C, LAYOUT, df_subcat, go, mo):
    _data = df_subcat[
        df_subcat['category'].isin(['Infrastructure', 'AI Engineering', 'Model Development', 'Applications', 'Models'])
        & (df_subcat['repos'] >= 10)
        & (df_subcat['weekly_stars'] > 0)
    ].copy()
    _data = _data.sort_values('weekly_stars', ascending=False).head(25)
    _data = _data.sort_values('weekly_stars', ascending=True)

    _fig = go.Figure(go.Bar(
        x=_data['weekly_stars'], y=_data['primary_subcat'], orientation='h',
        marker_color=[CAT_COLORS.get(_c, C['ink_3']) for _c in _data['category']],
        customdata=list(zip(_data['category'], _data['repos'], _data['total_stars'])),
        hovertemplate=(
            '<b>%{y}</b><br>Category: %{customdata[0]}<br>'
            '7-day stars: %{x:,.0f}<br>Repos: %{customdata[1]}<br>'
            'Total stars: %{customdata[2]:,.0f}<extra></extra>'
        ),
    ))
    _fig.update_layout(
        **LAYOUT,
        height=500,
        xaxis=dict(title='7-day new stars', showgrid=True, gridcolor=C['rule']),
        yaxis=dict(title='', showgrid=False),
    )
    mo.ui.plotly(_fig, config={"displayModeBar": False})
    return


@app.cell(hide_code=True)
def section_devactivity(C, F, mo):
    mo.Html(
        f'<div style="margin:44px 0 20px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["accent"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">'
        f'Developer Depth</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.6rem; font-weight:600;'
        f'color:{C["ink"]}; margin:0 0 8px;">Who’s building?</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.9rem; color:{C["ink_3"]}; '
        f'margin:0; line-height:1.5;">'
        f'Repo-scoped metrics from OpenDevData: only tracked repos, no project inflation. '
        f'Full-time: ≥10 active days in the last 28-day window. Part-time: 1–9 active days.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def stars_bar(C, LAYOUT, df_stars_forks, go, mo):
    _df = df_stars_forks.sort_values('stars_3m', ascending=True).tail(20).copy()
    _df['short_name'] = _df['repo'].apply(lambda r: r.split('/')[-1])
    _fig = go.Figure(go.Bar(
        x=_df['stars_3m'], y=_df['short_name'], orientation='h',
        marker_color=C['accent'],
        customdata=list(zip(_df['repo'], _df['forks_3m'])),
        hovertemplate='<b>%{customdata[0]}</b><br>Stars (3mo): %{x:,.0f}<br>Forks (3mo): %{customdata[1]:,.0f}<extra></extra>',
    ))
    _fig.update_layout(
        **LAYOUT,
        height=520,
        xaxis=dict(title='New stars, last 90 days', showgrid=True, gridcolor=C['rule']),
        yaxis=dict(title='', showgrid=False),
    )
    mo.vstack([
        mo.md("### Top 20 repos by stars, last 90 days"),
        mo.ui.plotly(_fig, config={"displayModeBar": False}),
    ])
    return


@app.cell(hide_code=True)
def contributors_bar(C, LAYOUT, df_contributors, go, mo):
    _df = df_contributors.nlargest(20, 'full_time').sort_values('full_time', ascending=True).copy()
    _df['short_name'] = _df['repo'].apply(lambda r: r.split('/')[-1])
    _fig = go.Figure()
    _fig.add_trace(go.Bar(
        x=_df['full_time'], y=_df['short_name'], orientation='h',
        name='Full-time (≥10 active days)',
        marker_color=C['healthy'],
        customdata=_df['repo'],
        hovertemplate='<b>%{customdata}</b><br>Full-time: %{x:,}<extra></extra>',
    ))
    _fig.add_trace(go.Bar(
        x=_df['part_time'], y=_df['short_name'], orientation='h',
        name='Part-time (1–9 active days)',
        marker_color=C['rule'],
        customdata=_df['repo'],
        hovertemplate='<b>%{customdata}</b><br>Part-time: %{x:,}<extra></extra>',
    ))
    _fig.update_layout(
        **LAYOUT,
        height=520,
        barmode='stack',
        xaxis=dict(title='Active contributors, last 90 days', showgrid=True, gridcolor=C['rule']),
        yaxis=dict(title='', showgrid=False),
    )
    mo.vstack([
        mo.md("### Full-time vs part-time contributors, top 20 repos"),
        mo.ui.plotly(_fig, config={"displayModeBar": False}),
    ])
    return


@app.cell(hide_code=True)
def fulltime_ratio_bar(C, LAYOUT, df_contributors, go, mo):
    _df = df_contributors[df_contributors['total_contributors'] >= 5].copy()
    _df['ft_ratio'] = _df['full_time'] / _df['total_contributors'] * 100
    _df = _df.nlargest(20, 'ft_ratio').sort_values('ft_ratio', ascending=True)
    _df['short_name'] = _df['repo'].apply(lambda r: r.split('/')[-1])
    _fig = go.Figure(go.Bar(
        x=_df['ft_ratio'], y=_df['short_name'], orientation='h',
        marker_color=C['healthy'],
        customdata=list(zip(_df['repo'], _df['full_time'], _df['total_contributors'])),
        hovertemplate='<b>%{customdata[0]}</b><br>FT ratio: %{x:.1f}%<br>FT: %{customdata[1]:,} / Total: %{customdata[2]:,}<extra></extra>',
    ))
    _fig.update_layout(
        **LAYOUT,
        height=520,
        xaxis=dict(title='Full-time contributor ratio (%)', showgrid=True, gridcolor=C['rule']),
        yaxis=dict(title='', showgrid=False),
    )
    mo.vstack([
        mo.md("### Full-time depth, top 20 repos by FT ratio (min 5 contributors)"),
        mo.ui.plotly(_fig, config={"displayModeBar": False}),
    ])
    return


@app.cell(hide_code=True)
def methodology(C, F, mo):
    mo.Html(
        f'<div style="margin-top:44px; padding-top:20px; border-top:1px solid {C["rule"]};">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["ink_3"]}; '
        f'letter-spacing:0.08em; text-transform:uppercase; margin-bottom:8px;">Methodology</div>'
        f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; line-height:1.5;">'
        f'Repo catalog from GoodAI List (goodailist.com). Developer activity from OSO via OpenDevData, over '
        f'28-day rolling activity windows. Star and fork events from GitHub Archive (last 90 days). '
        f'Full-time: ≥10 active days in the 28-day window. Part-time: 1–9 active days.</p>'
        f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; margin-top:8px;">'
        f'<strong>Source:</strong> '
        f'<a href="https://www.oso.xyz" style="color:{C["accent"]}">Open Source Observer</a>, '
        f'<a href="https://goodailist.com" style="color:{C["accent"]}">GoodAI List</a></p>'
        f'</div>'
    )
    return


if __name__ == "__main__":
    app.run()
